// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AddAdmin.swift

import Foundation

public struct AddAdmin: APIRequest {
	public typealias Response = AddAdminResponse

	public static let path = "/admin/add"
	public static let httpMethod = HTTPMethod.post

	public var personId: Int
	public var added: Bool
	public var auth: String

	public init(personId: Int, added: Bool, auth: String) {
		self.personId = personId
		self.added = added
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case personId = "person_id"
		case added
		case auth
	}
}

public extension LemmyInstance {
	func addAdmin(personId: Int, added: Bool, auth: String) async throws -> AddAdmin.Response {
		try await request(AddAdmin(personId: personId, added: added, auth: auth))
	}
}
