// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AddModToCommunity.swift

import Foundation

public struct AddModToCommunity: APIRequest {
	public typealias Response = AddModToCommunityResponse

	public static let path = "/community/mod"
	public static let httpMethod = HTTPMethod.post

	public var communityId: Int
	public var personId: Int
	public var added: Bool
	public var auth: String

	public init(communityId: Int, personId: Int, added: Bool, auth: String) {
		self.communityId = communityId
		self.personId = personId
		self.added = added
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case personId = "person_id"
		case added
		case auth
	}
}

public extension LemmyInstance {
	func addModToCommunity(
		communityId: Int,
		personId: Int,
		added: Bool,
		auth: String
	) async throws -> AddModToCommunity.Response {
		try await request(AddModToCommunity(
			communityId: communityId,
			personId: personId,
			added: added,
			auth: auth
		))
	}
}
