// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ApproveRegistrationApplication.swift

import Foundation

public struct ApproveRegistrationApplication: APIRequest {
	public typealias Response = RegistrationApplicationResponse

	public static let path = "/admin/registration_application/approve"
	public static let httpMethod = HTTPMethod.put

	public var id: Int32
	public var approve: Bool
	public var denyReason: String?
	public var auth: String

	public init(id: Int32, approve: Bool, denyReason: String? = nil, auth: String) {
		self.id = id
		self.approve = approve
		self.denyReason = denyReason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case approve
		case denyReason = "deny_reason"
		case auth
	}
}

public extension LemmyInstance {
	func approveRegistrationApplication(
		id: Int32,
		approve: Bool,
		denyReason: String? = nil,
		auth: String
	) async throws -> ApproveRegistrationApplication.Response {
		try await request(ApproveRegistrationApplication(
			id: id,
			approve: approve,
			denyReason: denyReason,
			auth: auth
		))
	}
}
