// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: BanPerson.swift

import Foundation

public struct BanPerson: APIRequest {
	public typealias Response = BanPersonResponse

	public static let path = "/user/ban"
	public static let httpMethod = HTTPMethod.post

	public var personId: Int
	public var ban: Bool
	public var removeData: Bool?
	public var reason: String?
	public var expires: Int?
	public var auth: String

	public init(
		personId: Int,
		ban: Bool,
		removeData: Bool? = nil,
		reason: String? = nil,
		expires: Int? = nil,
		auth: String
	) {
		self.personId = personId
		self.ban = ban
		self.removeData = removeData
		self.reason = reason
		self.expires = expires
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case personId = "person_id"
		case ban
		case removeData = "remove_data"
		case reason
		case expires
		case auth
	}
}

public extension LemmyInstance {
	func banPerson(
		personId: Int,
		ban: Bool,
		removeData: Bool? = nil,
		reason: String? = nil,
		expires: Int? = nil,
		auth: String
	) async throws -> BanPerson.Response {
		try await request(BanPerson(
			personId: personId,
			ban: ban,
			removeData: removeData,
			reason: reason,
			expires: expires,
			auth: auth
		))
	}
}
