// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: BlockPerson.swift

import Foundation

public struct BlockPerson: APIRequest {
	public typealias Response = BlockPersonResponse

	public static let path = "/user/block"
	public static let httpMethod = HTTPMethod.post

	public var personId: Int
	public var block: Bool
	public var auth: String

	public init(personId: Int, block: Bool, auth: String) {
		self.personId = personId
		self.block = block
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case personId = "person_id"
		case block
		case auth
	}
}

public extension LemmyInstance {
	func blockPerson(personId: Int, block: Bool, auth: String) async throws -> BlockPerson.Response {
		try await request(BlockPerson(personId: personId, block: block, auth: auth))
	}
}
