// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: BlockCommunity.swift

import Foundation

public struct BlockCommunity: APIRequest {
	public typealias Response = BlockCommunityResponse

	public static let path = "/community/block"
	public static let httpMethod = HTTPMethod.post

	public var communityId: Int
	public var block: Bool
	public var auth: String

	public init(communityId: Int, block: Bool, auth: String) {
		self.communityId = communityId
		self.block = block
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case block
		case auth
	}
}

public extension LemmyInstance {
	func blockCommunity(communityId: Int, block: Bool, auth: String) async throws -> BlockCommunity
		.Response
	{
		try await request(BlockCommunity(communityId: communityId, block: block, auth: auth))
	}
}
