// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CreatePost.swift

import Foundation

public struct CreatePost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post"
	public static let httpMethod = HTTPMethod.post

	public var name: String
	public var communityId: Int
	public var url: URL?
	public var body: String?
	public var honeypot: String?
	public var nsfw: Bool?
	public var languageId: Int?
	public var auth: String

	public init(
		name: String,
		communityId: Int,
		url: URL? = nil,
		body: String? = nil,
		honeypot: String? = nil,
		nsfw: Bool? = nil,
		languageId: Int? = nil,
		auth: String
	) {
		self.name = name
		self.communityId = communityId
		self.url = url
		self.body = body
		self.honeypot = honeypot
		self.nsfw = nsfw
		self.languageId = languageId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case name
		case communityId = "community_id"
		case url
		case body
		case honeypot
		case nsfw
		case languageId = "language_id"
		case auth
	}
}

public extension LemmyInstance {
	func createPost(
		name: String,
		communityId: Int,
		url: URL? = nil,
		body: String? = nil,
		honeypot: String? = nil,
		nsfw: Bool? = nil,
		languageId: Int? = nil,
		auth: String
	) async throws -> CreatePost.Response {
		try await request(CreatePost(
			name: name,
			communityId: communityId,
			url: url,
			body: body,
			honeypot: honeypot,
			nsfw: nsfw,
			languageId: languageId,
			auth: auth
		))
	}
}
