// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CreatePostReport.swift

import Foundation

public struct CreatePostReport: APIRequest {
	public typealias Response = PostReportResponse

	public static let path = "/post/report"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var reason: String
	public var auth: String

	public init(postId: Int, reason: String, auth: String) {
		self.postId = postId
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func createPostReport(postId: Int, reason: String, auth: String) async throws -> CreatePostReport
		.Response
	{
		try await request(CreatePostReport(postId: postId, reason: reason, auth: auth))
	}
}
