// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CreatePostLike.swift

import Foundation

public struct CreatePostLike: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/like"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var score: Int16
	public var auth: String

	public init(postId: Int, score: Int16, auth: String) {
		self.postId = postId
		self.score = score
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case score
		case auth
	}
}

public extension LemmyInstance {
	func createPostLike(postId: Int, score: Int16, auth: String) async throws -> CreatePostLike
		.Response
	{
		try await request(CreatePostLike(postId: postId, score: score, auth: auth))
	}
}
