// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CreateCustomEmoji.swift

import Foundation

public struct CreateCustomEmoji: APIRequest {
	public typealias Response = CustomEmojiResponse

	public static let path = "/custom_emoji"
	public static let httpMethod = HTTPMethod.post

	public var category: String
	public var shortcode: String
	public var imageURL: URL?
	public var altText: String
	public var keywords: [String]
	public var auth: String

	public init(
		category: String,
		shortcode: String,
		imageURL: URL? = nil,
		altText: String,
		keywords: [String],
		auth: String
	) {
		self.category = category
		self.shortcode = shortcode
		self.imageURL = imageURL
		self.altText = altText
		self.keywords = keywords
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case category
		case shortcode
		case imageURL = "image_url"
		case altText = "alt_text"
		case keywords
		case auth
	}
}

public extension LemmyInstance {
	func createCustomEmoji(
		category: String,
		shortcode: String,
		imageURL: URL? = nil,
		altText: String,
		keywords: [String],
		auth: String
	) async throws -> CreateCustomEmoji.Response {
		try await request(CreateCustomEmoji(
			category: category,
			shortcode: shortcode,
			imageURL: imageURL,
			altText: altText,
			keywords: keywords,
			auth: auth
		))
	}
}
