// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CreateComment.swift

import Foundation

public struct CreateComment: APIRequest {
	public typealias Response = CommentResponse

	public static let path = "/comment"
	public static let httpMethod = HTTPMethod.post

	public var content: String
	public var postId: Int
	public var parentId: Int?
	public var languageId: Int?
	public var formId: String?
	public var auth: String

	public init(
		content: String,
		postId: Int,
		parentId: Int? = nil,
		languageId: Int? = nil,
		formId: String? = nil,
		auth: String
	) {
		self.content = content
		self.postId = postId
		self.parentId = parentId
		self.languageId = languageId
		self.formId = formId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case content
		case postId = "post_id"
		case parentId = "parent_id"
		case languageId = "language_id"
		case formId = "form_id"
		case auth
	}
}

public extension LemmyInstance {
	func createComment(
		content: String,
		postId: Int,
		parentId: Int? = nil,
		languageId: Int? = nil,
		formId: String? = nil,
		auth: String
	) async throws -> CreateComment.Response {
		try await request(CreateComment(
			content: content,
			postId: postId,
			parentId: parentId,
			languageId: languageId,
			formId: formId,
			auth: auth
		))
	}
}
