// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeletePost.swift

import Foundation

public struct DeletePost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/delete"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var deleted: Bool
	public var auth: String

	public init(postId: Int, deleted: Bool, auth: String) {
		self.postId = postId
		self.deleted = deleted
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case deleted
		case auth
	}
}

public extension LemmyInstance {
	func deletePost(postId: Int, deleted: Bool, auth: String) async throws -> DeletePost.Response {
		try await request(DeletePost(postId: postId, deleted: deleted, auth: auth))
	}
}
