// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeleteComment.swift

import Foundation

public struct DeleteComment: APIRequest {
	public typealias Response = CommentResponse

	public static let path = "/comment/delete"
	public static let httpMethod = HTTPMethod.post

	public var commentId: Int
	public var deleted: Bool
	public var auth: String

	public init(commentId: Int, deleted: Bool, auth: String) {
		self.commentId = commentId
		self.deleted = deleted
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case commentId = "comment_id"
		case deleted
		case auth
	}
}

public extension LemmyInstance {
	func deleteComment(commentId: Int, deleted: Bool, auth: String) async throws -> DeleteComment
		.Response
	{
		try await request(DeleteComment(commentId: commentId, deleted: deleted, auth: auth))
	}
}
