// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeleteAccount.swift

import Foundation

public struct DeleteAccount: APIRequest {
	public typealias Response = DeleteAccountResponse

	public static let path = "/user/delete_account"
	public static let httpMethod = HTTPMethod.post

	public var password: String
	public var auth: String

	public init(password: String, auth: String) {
		self.password = password
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case password
		case auth
	}
}

public extension LemmyInstance {
	func deleteAccount(password: String, auth: String) async throws -> DeleteAccount.Response {
		try await request(DeleteAccount(password: password, auth: auth))
	}
}
