// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeleteCustomEmoji.swift

import Foundation

public struct DeleteCustomEmoji: APIRequest {
	public typealias Response = DeleteCustomEmojiResponse

	public static let path = "/custom_emoji/delete"
	public static let httpMethod = HTTPMethod.post

	public var id: Int
	public var auth: String

	public init(id: Int, auth: String) {
		self.id = id
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case auth
	}
}

public extension LemmyInstance {
	func deleteCustomEmoji(id: Int, auth: String) async throws -> DeleteCustomEmoji.Response {
		try await request(DeleteCustomEmoji(id: id, auth: auth))
	}
}
