// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeletePrivateMessage.swift

import Foundation

public struct DeletePrivateMessage: APIRequest {
	public typealias Response = PrivateMessageResponse

	public static let path = "/private_message/delete"
	public static let httpMethod = HTTPMethod.post

	public var privateMessageId: Int
	public var deleted: Bool
	public var auth: String

	public init(privateMessageId: Int, deleted: Bool, auth: String) {
		self.privateMessageId = privateMessageId
		self.deleted = deleted
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessageId = "private_message_id"
		case deleted
		case auth
	}
}

public extension LemmyInstance {
	func deletePrivateMessage(
		privateMessageId: Int,
		deleted: Bool,
		auth: String
	) async throws -> DeletePrivateMessage.Response {
		try await request(DeletePrivateMessage(
			privateMessageId: privateMessageId,
			deleted: deleted,
			auth: auth
		))
	}
}
