// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DistinguishComment.swift

import Foundation

public struct DistinguishComment: APIRequest {
	public typealias Response = CommentResponse

	public static let path = "/comment/distinguish"
	public static let httpMethod = HTTPMethod.post

	public var commentId: Int
	public var distinguished: Bool
	public var auth: String

	public init(commentId: Int, distinguished: Bool, auth: String) {
		self.commentId = commentId
		self.distinguished = distinguished
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case commentId = "comment_id"
		case distinguished
		case auth
	}
}

public extension LemmyInstance {
	func distinguishComment(
		commentId: Int,
		distinguished: Bool,
		auth: String
	) async throws -> DistinguishComment.Response {
		try await request(DistinguishComment(
			commentId: commentId,
			distinguished: distinguished,
			auth: auth
		))
	}
}
