// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EditComment.swift

import Foundation

public struct EditComment: APIRequest {
	public typealias Response = CommentResponse

	public static let path = "/comment"
	public static let httpMethod = HTTPMethod.put

	public var commentId: Int
	public var content: String?
	public var languageId: Int?
	public var formId: String?
	public var auth: String

	public init(
		commentId: Int,
		content: String? = nil,
		languageId: Int? = nil,
		formId: String? = nil,
		auth: String
	) {
		self.commentId = commentId
		self.content = content
		self.languageId = languageId
		self.formId = formId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case commentId = "comment_id"
		case content
		case languageId = "language_id"
		case formId = "form_id"
		case auth
	}
}

public extension LemmyInstance {
	func editComment(
		commentId: Int,
		content: String? = nil,
		languageId: Int? = nil,
		formId: String? = nil,
		auth: String
	) async throws -> EditComment.Response {
		try await request(EditComment(
			commentId: commentId,
			content: content,
			languageId: languageId,
			formId: formId,
			auth: auth
		))
	}
}
