// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EditPrivateMessage.swift

import Foundation

public struct EditPrivateMessage: APIRequest {
	public typealias Response = PrivateMessageResponse

	public static let path = "/private_message"
	public static let httpMethod = HTTPMethod.put

	public var privateMessageId: Int
	public var content: String
	public var auth: String

	public init(privateMessageId: Int, content: String, auth: String) {
		self.privateMessageId = privateMessageId
		self.content = content
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessageId = "private_message_id"
		case content
		case auth
	}
}

public extension LemmyInstance {
	func editPrivateMessage(
		privateMessageId: Int,
		content: String,
		auth: String
	) async throws -> EditPrivateMessage.Response {
		try await request(EditPrivateMessage(
			privateMessageId: privateMessageId,
			content: content,
			auth: auth
		))
	}
}
