// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EditPost.swift

import Foundation

public struct EditPost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post"
	public static let httpMethod = HTTPMethod.put

	public var postId: Int
	public var name: String?
	public var url: URL?
	public var body: String?
	public var nsfw: Bool?
	public var languageId: Int?
	public var auth: String

	public init(
		postId: Int,
		name: String? = nil,
		url: URL? = nil,
		body: String? = nil,
		nsfw: Bool? = nil,
		languageId: Int? = nil,
		auth: String
	) {
		self.postId = postId
		self.name = name
		self.url = url
		self.body = body
		self.nsfw = nsfw
		self.languageId = languageId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case name
		case url
		case body
		case nsfw
		case languageId = "language_id"
		case auth
	}
}

public extension LemmyInstance {
	func editPost(
		postId: Int,
		name: String? = nil,
		url: URL? = nil,
		body: String? = nil,
		nsfw: Bool? = nil,
		languageId: Int? = nil,
		auth: String
	) async throws -> EditPost.Response {
		try await request(EditPost(
			postId: postId,
			name: name,
			url: url,
			body: body,
			nsfw: nsfw,
			languageId: languageId,
			auth: auth
		))
	}
}
