// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EditCustomEmoji.swift

import Foundation

public struct EditCustomEmoji: APIRequest {
	public typealias Response = CustomEmojiResponse

	public static let path = "/custom_emoji"
	public static let httpMethod = HTTPMethod.put

	public var id: Int
	public var category: String
	public var imageUrl: URL?
	public var altText: String
	public var keywords: [String]
	public var auth: String

	public init(
		id: Int,
		category: String,
		imageUrl: URL? = nil,
		altText: String,
		keywords: [String],
		auth: String
	) {
		self.id = id
		self.category = category
		self.imageUrl = imageUrl
		self.altText = altText
		self.keywords = keywords
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case category
		case imageUrl = "image_url"
		case altText = "alt_text"
		case keywords
		case auth
	}
}

public extension LemmyInstance {
	func editCustomEmoji(
		id: Int,
		category: String,
		imageUrl: URL? = nil,
		altText: String,
		keywords: [String],
		auth: String
	) async throws -> EditCustomEmoji.Response {
		try await request(EditCustomEmoji(
			id: id,
			category: category,
			imageUrl: imageUrl,
			altText: altText,
			keywords: keywords,
			auth: auth
		))
	}
}
