// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EditCommunity.swift

import Foundation

public struct EditCommunity: APIRequest {
	public typealias Response = CommunityResponse

	public static let path = "/community"
	public static let httpMethod = HTTPMethod.put

	public var communityId: Int
	public var title: String?
	public var description: String?
	public var icon: String?
	public var banner: String?
	public var nsfw: Bool?
	public var postingRestrictedToMods: Bool?
	public var discussionLanguages: [Int?]
	public var auth: String

	public init(
		communityId: Int,
		title: String? = nil,
		description: String? = nil,
		icon: String? = nil,
		banner: String? = nil,
		nsfw: Bool? = nil,
		postingRestrictedToMods: Bool? = nil,
		discussionLanguages: [Int?],
		auth: String
	) {
		self.communityId = communityId
		self.title = title
		self.description = description
		self.icon = icon
		self.banner = banner
		self.nsfw = nsfw
		self.postingRestrictedToMods = postingRestrictedToMods
		self.discussionLanguages = discussionLanguages
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case title
		case description
		case icon
		case banner
		case nsfw
		case postingRestrictedToMods = "posting_restricted_to_mods"
		case discussionLanguages = "discussion_languages"
		case auth
	}
}

public extension LemmyInstance {
	func editCommunity(
		communityId: Int,
		title: String? = nil,
		description: String? = nil,
		icon: String? = nil,
		banner: String? = nil,
		nsfw: Bool? = nil,
		postingRestrictedToMods: Bool? = nil,
		discussionLanguages: [Int?],
		auth: String
	) async throws -> EditCommunity.Response {
		try await request(EditCommunity(
			communityId: communityId,
			title: title,
			description: description,
			icon: icon,
			banner: banner,
			nsfw: nsfw,
			postingRestrictedToMods: postingRestrictedToMods,
			discussionLanguages: discussionLanguages,
			auth: auth
		))
	}
}
