// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: FeaturePost.swift

import Foundation

public struct FeaturePost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/feature"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var featured: Bool
	public var featureType: PostFeatureType
	public var auth: String

	public init(postId: Int, featured: Bool, featureType: PostFeatureType, auth: String) {
		self.postId = postId
		self.featured = featured
		self.featureType = featureType
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case featured
		case featureType = "feature_type"
		case auth
	}
}

public extension LemmyInstance {
	func featurePost(
		postId: Int,
		featured: Bool,
		featureType: PostFeatureType,
		auth: String
	) async throws -> FeaturePost.Response {
		try await request(FeaturePost(
			postId: postId,
			featured: featured,
			featureType: featureType,
			auth: auth
		))
	}
}
