// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetBannedPersons.swift

import Foundation

public struct GetBannedPersons: APIRequest {
	public typealias Response = BannedPersonsResponse

	public static let path = "/user/banned"
	public static let httpMethod = HTTPMethod.get

	public var auth: String

	public init(auth: String) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func getBannedPersons(auth: String) async throws -> GetBannedPersons.Response {
		try await request(GetBannedPersons(auth: auth))
	}
}
