// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetCommunity.swift

import Foundation

public struct GetCommunity: APIRequest {
	public typealias Response = GetCommunityResponse

	public static let path = "/community"
	public static let httpMethod = HTTPMethod.get

	public var id: Int?
	public var name: String?
	public var auth: String?

	public init(id: Int? = nil, name: String? = nil, auth: String? = nil) {
		self.id = id
		self.name = name
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case name
		case auth
	}
}

public extension LemmyInstance {
	func getCommunity(
		id: Int? = nil,
		name: String? = nil,
		auth: String? = nil
	) async throws -> GetCommunity.Response {
		try await request(GetCommunity(id: id, name: name, auth: auth))
	}
}
