// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetComments.swift

import Foundation

public struct GetComments: APIRequest {
	public typealias Response = GetCommentsResponse

	public static let path = "/comment/list"
	public static let httpMethod = HTTPMethod.get

	public var type: ListingType?
	public var sort: CommentSortType?
	public var maxDepth: Int32?
	public var page: Int?
	public var limit: Int?
	public var communityId: Int?
	public var communityName: String?
	public var postId: Int?
	public var parentId: Int?
	public var savedOnly: Bool?
	public var auth: String?

	public init(
		type: ListingType? = nil,
		sort: CommentSortType? = nil,
		maxDepth: Int32? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		communityId: Int? = nil,
		communityName: String? = nil,
		postId: Int? = nil,
		parentId: Int? = nil,
		savedOnly: Bool? = nil,
		auth: String? = nil
	) {
		self.type = type
		self.sort = sort
		self.maxDepth = maxDepth
		self.page = page
		self.limit = limit
		self.communityId = communityId
		self.communityName = communityName
		self.postId = postId
		self.parentId = parentId
		self.savedOnly = savedOnly
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case type = "type_"
		case sort
		case maxDepth = "max_depth"
		case page
		case limit
		case communityId = "community_id"
		case communityName = "community_name"
		case postId = "post_id"
		case parentId = "parent_id"
		case savedOnly = "saved_only"
		case auth
	}
}

public extension LemmyInstance {
	func getComments(
		type: ListingType? = nil,
		sort: CommentSortType? = nil,
		maxDepth: Int32? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		communityId: Int? = nil,
		communityName: String? = nil,
		postId: Int? = nil,
		parentId: Int? = nil,
		savedOnly: Bool? = nil,
		auth: String? = nil
	) async throws -> GetComments.Response {
		try await request(GetComments(
			type: type,
			sort: sort,
			maxDepth: maxDepth,
			page: page,
			limit: limit,
			communityId: communityId,
			communityName: communityName,
			postId: postId,
			parentId: parentId,
			savedOnly: savedOnly,
			auth: auth
		))
	}
}
