// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetCaptcha.swift

import Foundation

public struct GetCaptcha: APIRequest {
	public typealias Response = GetCaptchaResponse

	public static let path = "/user/get_captcha"
	public static let httpMethod = HTTPMethod.get

	public var auth: String?

	public init(auth: String? = nil) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func getCaptcha(auth: String? = nil) async throws -> GetCaptcha.Response {
		try await request(GetCaptcha(auth: auth))
	}
}
