// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetComment.swift

import Foundation

public struct GetComment: APIRequest {
	public typealias Response = CommentResponse

	public static let path = "/comment"
	public static let httpMethod = HTTPMethod.get

	public var id: Int
	public var auth: String?

	public init(id: Int, auth: String? = nil) {
		self.id = id
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case auth
	}
}

public extension LemmyInstance {
	func getComment(id: Int, auth: String? = nil) async throws -> GetComment.Response {
		try await request(GetComment(id: id, auth: auth))
	}
}
