// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetFederatedInstances.swift

import Foundation

public struct GetFederatedInstances: APIRequest {
	public typealias Response = GetFederatedInstancesResponse

	public static let path = "/federated_instances"
	public static let httpMethod = HTTPMethod.get

	public var auth: String?

	public init(auth: String? = nil) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func getFederatedInstances(auth: String? = nil) async throws -> GetFederatedInstances.Response {
		try await request(GetFederatedInstances(auth: auth))
	}
}
