// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetPosts.swift

import Foundation

public struct GetPosts: APIRequest {
	public typealias Response = GetPostsResponse

	public static let path = "/post/list"
	public static let httpMethod = HTTPMethod.get

	public var type: ListingType?
	public var sort: SortType?
	public var page: Int?
	public var limit: Int?
	public var communityId: Int?
	public var communityName: String?
	public var savedOnly: Bool?
	public var auth: String?

	public init(
		type: ListingType? = nil,
		sort: SortType? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		communityId: Int? = nil,
		communityName: String? = nil,
		savedOnly: Bool? = nil,
		auth: String? = nil
	) {
		self.type = type
		self.sort = sort
		self.page = page
		self.limit = limit
		self.communityId = communityId
		self.communityName = communityName
		self.savedOnly = savedOnly
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case type = "type_"
		case sort
		case page
		case limit
		case communityId = "community_id"
		case communityName = "community_name"
		case savedOnly = "saved_only"
		case auth
	}
}

public extension LemmyInstance {
	func getPosts(
		type: ListingType? = nil,
		sort: SortType? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		communityId: Int? = nil,
		communityName: String? = nil,
		savedOnly: Bool? = nil,
		auth: String? = nil
	) async throws -> GetPosts.Response {
		try await request(GetPosts(
			type: type,
			sort: sort,
			page: page,
			limit: limit,
			communityId: communityId,
			communityName: communityName,
			savedOnly: savedOnly,
			auth: auth
		))
	}
}
