// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetPost.swift

import Foundation

public struct GetPost: APIRequest {
	public typealias Response = GetPostResponse

	public static let path = "/post"
	public static let httpMethod = HTTPMethod.get

	public var id: Int?
	public var commentId: Int?
	public var auth: String?

	public init(id: Int? = nil, commentId: Int? = nil, auth: String? = nil) {
		self.id = id
		self.commentId = commentId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case commentId = "comment_id"
		case auth
	}
}

public extension LemmyInstance {
	func getPost(id: Int? = nil, commentId: Int? = nil, auth: String? = nil) async throws -> GetPost
		.Response
	{
		try await request(GetPost(id: id, commentId: commentId, auth: auth))
	}
}
