// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetReplies.swift

import Foundation

public struct GetReplies: APIRequest {
	public typealias Response = GetRepliesResponse

	public static let path = "/user/replies"
	public static let httpMethod = HTTPMethod.get

	public var sort: CommentSortType?
	public var page: Int?
	public var limit: Int?
	public var unreadOnly: Bool?
	public var auth: String

	public init(
		sort: CommentSortType? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		unreadOnly: Bool? = nil,
		auth: String
	) {
		self.sort = sort
		self.page = page
		self.limit = limit
		self.unreadOnly = unreadOnly
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case sort
		case page
		case limit
		case unreadOnly = "unread_only"
		case auth
	}
}

public extension LemmyInstance {
	func getReplies(
		sort: CommentSortType? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		unreadOnly: Bool? = nil,
		auth: String
	) async throws -> GetReplies.Response {
		try await request(GetReplies(
			sort: sort,
			page: page,
			limit: limit,
			unreadOnly: unreadOnly,
			auth: auth
		))
	}
}
