// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetReportCount.swift

import Foundation

public struct GetReportCount: APIRequest {
	public typealias Response = GetReportCountResponse

	public static let path = "/user/report_count"
	public static let httpMethod = HTTPMethod.get

	public var communityId: Int?
	public var auth: String

	public init(communityId: Int? = nil, auth: String) {
		self.communityId = communityId
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case auth
	}
}

public extension LemmyInstance {
	func getReportCount(communityId: Int? = nil, auth: String) async throws -> GetReportCount
		.Response
	{
		try await request(GetReportCount(communityId: communityId, auth: auth))
	}
}
