// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetSite.swift

import Foundation

public struct GetSite: APIRequest {
	public typealias Response = GetSiteResponse

	public static let path = "/site"
	public static let httpMethod = HTTPMethod.get

	public var auth: String?

	public init(auth: String? = nil) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func getSite(auth: String? = nil) async throws -> GetSite.Response {
		try await request(GetSite(auth: auth))
	}
}
