// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetSiteMetadata.swift

import Foundation

public struct GetSiteMetadata: APIRequest {
	public typealias Response = GetSiteMetadataResponse

	public static let path = "/post/site_metadata"
	public static let httpMethod = HTTPMethod.get

	public var url: URL?

	public init(url: URL? = nil) {
		self.url = url
	}

	public enum CodingKeys: String, CodingKey {
		case url
	}
}

public extension LemmyInstance {
	func getSiteMetadata(url: URL? = nil) async throws -> GetSiteMetadata.Response {
		try await request(GetSiteMetadata(url: url))
	}
}
