// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetUnreadCount.swift

import Foundation

public struct GetUnreadCount: APIRequest {
	public typealias Response = GetUnreadCountResponse

	public static let path = "/user/unread_count"
	public static let httpMethod = HTTPMethod.get

	public var auth: String

	public init(auth: String) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func getUnreadCount(auth: String) async throws -> GetUnreadCount.Response {
		try await request(GetUnreadCount(auth: auth))
	}
}
