// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: HideCommunity.swift

import Foundation

public struct HideCommunity: APIRequest {
	public typealias Response = CommunityResponse

	public static let path = "/community/hide"
	public static let httpMethod = HTTPMethod.put

	public var communityId: Int
	public var hidden: Bool
	public var reason: String?
	public var auth: String

	public init(communityId: Int, hidden: Bool, reason: String? = nil, auth: String) {
		self.communityId = communityId
		self.hidden = hidden
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case hidden
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func hideCommunity(
		communityId: Int,
		hidden: Bool,
		reason: String? = nil,
		auth: String
	) async throws -> HideCommunity.Response {
		try await request(HideCommunity(
			communityId: communityId,
			hidden: hidden,
			reason: reason,
			auth: auth
		))
	}
}
