// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LeaveAdmin.swift

import Foundation

public struct LeaveAdmin: APIRequest {
	public typealias Response = GetSiteResponse

	public static let path = "/user/leave_admin"
	public static let httpMethod = HTTPMethod.post

	public var auth: String

	public init(auth: String) {
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case auth
	}
}

public extension LemmyInstance {
	func leaveAdmin(auth: String) async throws -> LeaveAdmin.Response {
		try await request(LeaveAdmin(auth: auth))
	}
}
