// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListPrivateMessageReports.swift

import Foundation

public struct ListPrivateMessageReports: APIRequest {
	public typealias Response = ListPrivateMessageReportsResponse

	public static let path = "/private_message/report/list"
	public static let httpMethod = HTTPMethod.get

	public var page: Int?
	public var limit: Int?
	public var unresolvedOnly: Bool?
	public var auth: String

	public init(page: Int? = nil, limit: Int? = nil, unresolvedOnly: Bool? = nil, auth: String) {
		self.page = page
		self.limit = limit
		self.unresolvedOnly = unresolvedOnly
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case page
		case limit
		case unresolvedOnly = "unresolved_only"
		case auth
	}
}

public extension LemmyInstance {
	func listPrivateMessageReports(
		page: Int? = nil,
		limit: Int? = nil,
		unresolvedOnly: Bool? = nil,
		auth: String
	) async throws -> ListPrivateMessageReports.Response {
		try await request(ListPrivateMessageReports(
			page: page,
			limit: limit,
			unresolvedOnly: unresolvedOnly,
			auth: auth
		))
	}
}
