// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListCommunities.swift

import Foundation

public struct ListCommunities: APIRequest {
	public typealias Response = ListCommunitiesResponse

	public static let path = "/community/list"
	public static let httpMethod = HTTPMethod.get

	public var type: ListingType?
	public var sort: SortType?
	public var showNSFW: Bool?
	public var page: Int?
	public var limit: Int?
	public var auth: String?

	public init(
		type: ListingType? = nil,
		sort: SortType? = nil,
		showNSFW: Bool? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		auth: String? = nil
	) {
		self.type = type
		self.sort = sort
		self.showNSFW = showNSFW
		self.page = page
		self.limit = limit
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case type = "type_"
		case sort
		case showNSFW = "show_nsfw"
		case page
		case limit
		case auth
	}
}

public extension LemmyInstance {
	func listCommunities(
		type: ListingType? = nil,
		sort: SortType? = nil,
		showNSFW: Bool? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		auth: String? = nil
	) async throws -> ListCommunities.Response {
		try await request(ListCommunities(
			type: type,
			sort: sort,
			showNSFW: showNSFW,
			page: page,
			limit: limit,
			auth: auth
		))
	}
}
