// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LockPost.swift

import Foundation

public struct LockPost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/lock"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var locked: Bool
	public var auth: String

	public init(postId: Int, locked: Bool, auth: String) {
		self.postId = postId
		self.locked = locked
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case locked
		case auth
	}
}

public extension LemmyInstance {
	func lockPost(postId: Int, locked: Bool, auth: String) async throws -> LockPost.Response {
		try await request(LockPost(postId: postId, locked: locked, auth: auth))
	}
}
