// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Login.swift

import Foundation

public struct Login: APIRequest {
	public typealias Response = LoginResponse

	public static let path = "/user/login"
	public static let httpMethod = HTTPMethod.post

	public var usernameOrEmail: String
	public var password: String
	public var totp2faToken: String?

	public init(usernameOrEmail: String, password: String, totp2faToken: String? = nil) {
		self.usernameOrEmail = usernameOrEmail
		self.password = password
		self.totp2faToken = totp2faToken
	}

	public enum CodingKeys: String, CodingKey {
		case usernameOrEmail = "username_or_email"
		case password
		case totp2faToken = "totp_2fa_token"
	}
}

public extension LemmyInstance {
	func login(
		usernameOrEmail: String,
		password: String,
		totp2faToken: String? = nil
	) async throws -> Login.Response {
		try await request(Login(
			usernameOrEmail: usernameOrEmail,
			password: password,
			totp2faToken: totp2faToken
		))
	}
}
