// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: MarkPostAsRead.swift

import Foundation

public struct MarkPostAsRead: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/mark_as_read"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var read: Bool
	public var auth: String

	public init(postId: Int, read: Bool, auth: String) {
		self.postId = postId
		self.read = read
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case read
		case auth
	}
}

public extension LemmyInstance {
	func markPostAsRead(postId: Int, read: Bool, auth: String) async throws -> MarkPostAsRead
		.Response
	{
		try await request(MarkPostAsRead(postId: postId, read: read, auth: auth))
	}
}
