// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: MarkPersonMentionAsRead.swift

import Foundation

public struct MarkPersonMentionAsRead: APIRequest {
	public typealias Response = PersonMentionResponse

	public static let path = "/user/mention/mark_as_read"
	public static let httpMethod = HTTPMethod.post

	public var personMentionId: Int
	public var read: Bool
	public var auth: String

	public init(personMentionId: Int, read: Bool, auth: String) {
		self.personMentionId = personMentionId
		self.read = read
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case personMentionId = "person_mention_id"
		case read
		case auth
	}
}

public extension LemmyInstance {
	func markPersonMentionAsRead(
		personMentionId: Int,
		read: Bool,
		auth: String
	) async throws -> MarkPersonMentionAsRead.Response {
		try await request(MarkPersonMentionAsRead(
			personMentionId: personMentionId,
			read: read,
			auth: auth
		))
	}
}
