// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PurgePost.swift

import Foundation

public struct PurgePost: APIRequest {
	public typealias Response = PurgeItemResponse

	public static let path = "/admin/post"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var reason: String?
	public var auth: String

	public init(postId: Int, reason: String? = nil, auth: String) {
		self.postId = postId
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func purgePost(postId: Int, reason: String? = nil, auth: String) async throws -> PurgePost
		.Response
	{
		try await request(PurgePost(postId: postId, reason: reason, auth: auth))
	}
}
