// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PurgeComment.swift

import Foundation

public struct PurgeComment: APIRequest {
	public typealias Response = PurgeItemResponse

	public static let path = "/admin/comment"
	public static let httpMethod = HTTPMethod.post

	public var commentId: Int
	public var reason: String?
	public var auth: String

	public init(commentId: Int, reason: String? = nil, auth: String) {
		self.commentId = commentId
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case commentId = "comment_id"
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func purgeComment(commentId: Int, reason: String? = nil, auth: String) async throws -> PurgeComment
		.Response
	{
		try await request(PurgeComment(commentId: commentId, reason: reason, auth: auth))
	}
}
