// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PurgeCommunity.swift

import Foundation

public struct PurgeCommunity: APIRequest {
	public typealias Response = PurgeItemResponse

	public static let path = "/admin/community"
	public static let httpMethod = HTTPMethod.post

	public var communityId: Int
	public var reason: String?
	public var auth: String

	public init(communityId: Int, reason: String? = nil, auth: String) {
		self.communityId = communityId
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func purgeCommunity(
		communityId: Int,
		reason: String? = nil,
		auth: String
	) async throws -> PurgeCommunity.Response {
		try await request(PurgeCommunity(communityId: communityId, reason: reason, auth: auth))
	}
}
