// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RemoveCommunity.swift

import Foundation

public struct RemoveCommunity: APIRequest {
	public typealias Response = CommunityResponse

	public static let path = "/community/remove"
	public static let httpMethod = HTTPMethod.post

	public var communityId: Int
	public var removed: Bool
	public var reason: String?
	public var expires: Int?
	public var auth: String

	public init(
		communityId: Int,
		removed: Bool,
		reason: String? = nil,
		expires: Int? = nil,
		auth: String
	) {
		self.communityId = communityId
		self.removed = removed
		self.reason = reason
		self.expires = expires
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case removed
		case reason
		case expires
		case auth
	}
}

public extension LemmyInstance {
	func removeCommunity(
		communityId: Int,
		removed: Bool,
		reason: String? = nil,
		expires: Int? = nil,
		auth: String
	) async throws -> RemoveCommunity.Response {
		try await request(RemoveCommunity(
			communityId: communityId,
			removed: removed,
			reason: reason,
			expires: expires,
			auth: auth
		))
	}
}
