// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RemovePost.swift

import Foundation

public struct RemovePost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/remove"
	public static let httpMethod = HTTPMethod.post

	public var postId: Int
	public var removed: Bool
	public var reason: String?
	public var auth: String

	public init(postId: Int, removed: Bool, reason: String? = nil, auth: String) {
		self.postId = postId
		self.removed = removed
		self.reason = reason
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case removed
		case reason
		case auth
	}
}

public extension LemmyInstance {
	func removePost(
		postId: Int,
		removed: Bool,
		reason: String? = nil,
		auth: String
	) async throws -> RemovePost.Response {
		try await request(RemovePost(postId: postId, removed: removed, reason: reason, auth: auth))
	}
}
