// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ResolveCommentReport.swift

import Foundation

public struct ResolveCommentReport: APIRequest {
	public typealias Response = CommentReportResponse

	public static let path = "/comment/report/resolve"
	public static let httpMethod = HTTPMethod.put

	public var reportId: Int
	public var resolved: Bool
	public var auth: String

	public init(reportId: Int, resolved: Bool, auth: String) {
		self.reportId = reportId
		self.resolved = resolved
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case reportId = "report_id"
		case resolved
		case auth
	}
}

public extension LemmyInstance {
	func resolveCommentReport(
		reportId: Int,
		resolved: Bool,
		auth: String
	) async throws -> ResolveCommentReport.Response {
		try await request(ResolveCommentReport(reportId: reportId, resolved: resolved, auth: auth))
	}
}
