// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SavePost.swift

import Foundation

public struct SavePost: APIRequest {
	public typealias Response = PostResponse

	public static let path = "/post/save"
	public static let httpMethod = HTTPMethod.put

	public var postId: Int
	public var save: Bool
	public var auth: String

	public init(postId: Int, save: Bool, auth: String) {
		self.postId = postId
		self.save = save
		self.auth = auth
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case save
		case auth
	}
}

public extension LemmyInstance {
	func savePost(postId: Int, save: Bool, auth: String) async throws -> SavePost.Response {
		try await request(SavePost(postId: postId, save: save, auth: auth))
	}
}
