// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: VerifyEmail.swift

import Foundation

public struct VerifyEmail: APIRequest {
	public typealias Response = VerifyEmailResponse

	public static let path = "/user/verify_email"
	public static let httpMethod = HTTPMethod.post

	public var token: String

	public init(token: String) {
		self.token = token
	}

	public enum CodingKeys: String, CodingKey {
		case token
	}
}

public extension LemmyInstance {
	func verifyEmail(token: String) async throws -> VerifyEmail.Response {
		try await request(VerifyEmail(token: token))
	}
}
