// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ActivityUpdateForm.swift

import AnyCodable
import Foundation

public struct ActivityUpdateForm: Codable {
	public var data: AnyCodable?
	public var local: Bool?
	public var updated: Date?
	public var sensitive: Bool?

	public init(
		data: AnyCodable? = nil,
		local: Bool? = nil,
		updated: Date? = nil,
		sensitive: Bool? = nil
	) {
		self.data = data
		self.local = local
		self.updated = updated
		self.sensitive = sensitive
	}

	public enum CodingKeys: String, CodingKey {
		case data
		case local
		case updated
		case sensitive
	}
}
