// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ActivityInsertForm.swift

import AnyCodable
import Foundation

public struct ActivityInsertForm: Codable {
	public var data: AnyCodable?
	public var local: Bool?
	public var updated: Date?
	public var apId: String
	public var sensitive: Bool?

	public init(
		data: AnyCodable? = nil,
		local: Bool? = nil,
		updated: Date? = nil,
		apId: String,
		sensitive: Bool? = nil
	) {
		self.data = data
		self.local = local
		self.updated = updated
		self.apId = apId
		self.sensitive = sensitive
	}

	public enum CodingKeys: String, CodingKey {
		case data
		case local
		case updated
		case apId = "ap_id"
		case sensitive
	}
}
