// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AddAdminResponse.swift

import Foundation

public struct AddAdminResponse: Codable {
	public var admins: [PersonView]

	public init(admins: [PersonView]) {
		self.admins = admins
	}

	public enum CodingKeys: String, CodingKey {
		case admins
	}
}
