// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AddModToCommunityResponse.swift

import Foundation

public struct AddModToCommunityResponse: Codable {
	public var moderators: [CommunityModeratorView]

	public init(moderators: [CommunityModeratorView]) {
		self.moderators = moderators
	}

	public enum CodingKeys: String, CodingKey {
		case moderators
	}
}
