// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AdminPurgePostView.swift

import Foundation

public struct AdminPurgePostView: Codable {
	public var adminPurgePost: AdminPurgePost
	public var admin: Person?
	public var community: Community

	public init(adminPurgePost: AdminPurgePost, admin: Person? = nil, community: Community) {
		self.adminPurgePost = adminPurgePost
		self.admin = admin
		self.community = community
	}

	public enum CodingKeys: String, CodingKey {
		case adminPurgePost = "admin_purge_post"
		case admin
		case community
	}
}
