// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AdminPurgeCommentForm.swift

import Foundation

public struct AdminPurgeCommentForm: Codable {
	public var adminPersonId: Int
	public var postId: Int
	public var reason: String?

	public init(adminPersonId: Int, postId: Int, reason: String? = nil) {
		self.adminPersonId = adminPersonId
		self.postId = postId
		self.reason = reason
	}

	public enum CodingKeys: String, CodingKey {
		case adminPersonId = "admin_person_id"
		case postId = "post_id"
		case reason
	}
}
