// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AdminPurgeCommentView.swift

import Foundation

public struct AdminPurgeCommentView: Codable {
	public var adminPurgeComment: AdminPurgeComment
	public var admin: Person?
	public var post: Post

	public init(adminPurgeComment: AdminPurgeComment, admin: Person? = nil, post: Post) {
		self.adminPurgeComment = adminPurgeComment
		self.admin = admin
		self.post = post
	}

	public enum CodingKeys: String, CodingKey {
		case adminPurgeComment = "admin_purge_comment"
		case admin
		case post
	}
}
