// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AdminPurgePersonView.swift

import Foundation

public struct AdminPurgePersonView: Codable {
	public var adminPurgePerson: AdminPurgePerson
	public var admin: Person?

	public init(adminPurgePerson: AdminPurgePerson, admin: Person? = nil) {
		self.adminPurgePerson = adminPurgePerson
		self.admin = admin
	}

	public enum CodingKeys: String, CodingKey {
		case adminPurgePerson = "admin_purge_person"
		case admin
	}
}
