// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: AdminPurgeComment.swift

import Foundation

public struct AdminPurgeComment: Codable {
	public var id: Int32
	public var adminPersonId: Int
	public var postId: Int
	public var reason: String?
	public var when: Date?

	public init(id: Int32, adminPersonId: Int, postId: Int, reason: String? = nil, when: Date? = nil) {
		self.id = id
		self.adminPersonId = adminPersonId
		self.postId = postId
		self.reason = reason
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case adminPersonId = "admin_person_id"
		case postId = "post_id"
		case reason
		case when = "when_"
	}
}
