// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: BannedPersonsResponse.swift

import Foundation

public struct BannedPersonsResponse: Codable {
	public var banned: [PersonView]

	public init(banned: [PersonView]) {
		self.banned = banned
	}

	public enum CodingKeys: String, CodingKey {
		case banned
	}
}
