// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: BanPersonResponse.swift

import Foundation

public struct BanPersonResponse: Codable {
	public var personView: PersonView
	public var banned: Bool

	public init(personView: PersonView, banned: Bool) {
		self.personView = personView
		self.banned = banned
	}

	public enum CodingKeys: String, CodingKey {
		case personView = "person_view"
		case banned
	}
}
