// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CaptchaAnswer.swift

import Foundation

public struct CaptchaAnswer: Codable {
	public var id: Int32
	public var uuid: UUID
	public var answer: String
	public var published: Date?

	public init(id: Int32, uuid: UUID, answer: String, published: Date? = nil) {
		self.id = id
		self.uuid = uuid
		self.answer = answer
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case uuid
		case answer
		case published
	}
}
