// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CaptchaAnswerForm.swift

import Foundation

public struct CaptchaAnswerForm: Codable {
	public var answer: String

	public init(answer: String) {
		self.answer = answer
	}

	public enum CodingKeys: String, CodingKey {
		case answer
	}
}
