// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CaptchaResponse.swift

import Foundation

public struct CaptchaResponse: Codable {
	public var png: String
	public var wav: String
	public var uuid: String

	public init(png: String, wav: String, uuid: String) {
		self.png = png
		self.wav = wav
		self.uuid = uuid
	}

	public enum CodingKeys: String, CodingKey {
		case png
		case wav
		case uuid
	}
}
