// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityResponse.swift

import Foundation

public struct CommunityResponse: Codable {
	public var communityView: CommunityView
	public var discussionLanguages: [Int]

	public init(communityView: CommunityView, discussionLanguages: [Int]) {
		self.communityView = communityView
		self.discussionLanguages = discussionLanguages
	}

	public enum CodingKeys: String, CodingKey {
		case communityView = "community_view"
		case discussionLanguages = "discussion_languages"
	}
}
