// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityPersonBanForm.swift

import Foundation

public struct CommunityPersonBanForm: Codable {
	public var communityId: Int
	public var personId: Int
	public var expires: Date?

	public init(communityId: Int, personId: Int, expires: Date? = nil) {
		self.communityId = communityId
		self.personId = personId
		self.expires = expires
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case personId = "person_id"
		case expires
	}
}
