// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentReportResponse.swift

import Foundation

public struct CommentReportResponse: Codable {
	public var commentReportView: CommentReportView

	public init(commentReportView: CommentReportView) {
		self.commentReportView = commentReportView
	}

	public enum CodingKeys: String, CodingKey {
		case commentReportView = "comment_report_view"
	}
}
