// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentSavedForm.swift

import Foundation

public struct CommentSavedForm: Codable {
	public var commentId: Int
	public var personId: Int

	public init(commentId: Int, personId: Int) {
		self.commentId = commentId
		self.personId = personId
	}

	public enum CodingKeys: String, CodingKey {
		case commentId = "comment_id"
		case personId = "person_id"
	}
}
