// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityView.swift

import Foundation

public struct CommunityView: Codable {
	public var community: Community
	public var subscribed: SubscribedType
	public var blocked: Bool
	public var counts: CommunityAggregates

	public init(
		community: Community,
		subscribed: SubscribedType,
		blocked: Bool,
		counts: CommunityAggregates
	) {
		self.community = community
		self.subscribed = subscribed
		self.blocked = blocked
		self.counts = counts
	}

	public enum CodingKeys: String, CodingKey {
		case community
		case subscribed
		case blocked
		case counts
	}
}
