// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityBlockView.swift

import Foundation

public struct CommunityBlockView: Codable {
	public var person: Person
	public var community: Community

	public init(person: Person, community: Community) {
		self.person = person
		self.community = community
	}

	public enum CodingKeys: String, CodingKey {
		case person
		case community
	}
}
