// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityModeratorForm.swift

import Foundation

public struct CommunityModeratorForm: Codable {
	public var communityId: Int
	public var personId: Int

	public init(communityId: Int, personId: Int) {
		self.communityId = communityId
		self.personId = personId
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case personId = "person_id"
	}
}
