// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityInsertForm.swift

import Foundation

public struct CommunityInsertForm: Codable {
	public var name: String
	public var title: String
	public var description: String?
	public var removed: Bool?
	public var published: Date?
	public var updated: Date?
	public var deleted: Bool?
	public var nsfw: Bool?
	public var actorId: String?
	public var local: Bool?
	public var privateKey: String?
	public var publicKey: String?
	public var lastRefreshedAt: Date?
	public var icon: String?
	public var banner: String?
	public var followersUrl: URL?
	public var inboxUrl: URL?
	public var sharedInboxUrl: URL?
	public var moderatorsUrl: URL?
	public var featuredUrl: URL?
	public var hidden: Bool?
	public var postingRestrictedToMods: Bool?
	public var instanceId: Int

	public init(
		name: String,
		title: String,
		description: String? = nil,
		removed: Bool? = nil,
		published: Date? = nil,
		updated: Date? = nil,
		deleted: Bool? = nil,
		nsfw: Bool? = nil,
		actorId: String? = nil,
		local: Bool? = nil,
		privateKey: String? = nil,
		publicKey: String? = nil,
		lastRefreshedAt: Date? = nil,
		icon: String? = nil,
		banner: String? = nil,
		followersUrl: URL? = nil,
		inboxUrl: URL? = nil,
		sharedInboxUrl: URL? = nil,
		moderatorsUrl: URL? = nil,
		featuredUrl: URL? = nil,
		hidden: Bool? = nil,
		postingRestrictedToMods: Bool? = nil,
		instanceId: Int
	) {
		self.name = name
		self.title = title
		self.description = description
		self.removed = removed
		self.published = published
		self.updated = updated
		self.deleted = deleted
		self.nsfw = nsfw
		self.actorId = actorId
		self.local = local
		self.privateKey = privateKey
		self.publicKey = publicKey
		self.lastRefreshedAt = lastRefreshedAt
		self.icon = icon
		self.banner = banner
		self.followersUrl = followersUrl
		self.inboxUrl = inboxUrl
		self.sharedInboxUrl = sharedInboxUrl
		self.moderatorsUrl = moderatorsUrl
		self.featuredUrl = featuredUrl
		self.hidden = hidden
		self.postingRestrictedToMods = postingRestrictedToMods
		self.instanceId = instanceId
	}

	public enum CodingKeys: String, CodingKey {
		case name
		case title
		case description
		case removed
		case published
		case updated
		case deleted
		case nsfw
		case actorId = "actor_id"
		case local
		case privateKey = "private_key"
		case publicKey = "public_key"
		case lastRefreshedAt = "last_refreshed_at"
		case icon
		case banner
		case followersUrl = "followers_url"
		case inboxUrl = "inbox_url"
		case sharedInboxUrl = "shared_inbox_url"
		case moderatorsUrl = "moderators_url"
		case featuredUrl = "featured_url"
		case hidden
		case postingRestrictedToMods = "posting_restricted_to_mods"
		case instanceId = "instance_id"
	}
}
