// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityFollowerForm.swift

import Foundation

public struct CommunityFollowerForm: Codable {
	public var communityId: Int
	public var personId: Int
	public var pending: Bool

	public init(communityId: Int, personId: Int, pending: Bool) {
		self.communityId = communityId
		self.personId = personId
		self.pending = pending
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case personId = "person_id"
		case pending
	}
}
