// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityPersonBan.swift

import Foundation

public struct CommunityPersonBan: Codable {
	public var id: Int32
	public var communityId: Int
	public var personId: Int
	public var published: Date?
	public var expires: Date?

	public init(
		id: Int32,
		communityId: Int,
		personId: Int,
		published: Date? = nil,
		expires: Date? = nil
	) {
		self.id = id
		self.communityId = communityId
		self.personId = personId
		self.published = published
		self.expires = expires
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case communityId = "community_id"
		case personId = "person_id"
		case published
		case expires
	}
}
