// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentReportForm.swift

import Foundation

public struct CommentReportForm: Codable {
	public var creatorId: Int
	public var commentId: Int
	public var originalCommentText: String
	public var reason: String

	public init(creatorId: Int, commentId: Int, originalCommentText: String, reason: String) {
		self.creatorId = creatorId
		self.commentId = commentId
		self.originalCommentText = originalCommentText
		self.reason = reason
	}

	public enum CodingKeys: String, CodingKey {
		case creatorId = "creator_id"
		case commentId = "comment_id"
		case originalCommentText = "original_comment_text"
		case reason
	}
}
