// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Comment.swift

import Foundation

public struct Comment: Codable {
	public var id: Int
	public var creatorId: Int
	public var postId: Int
	public var content: String
	public var removed: Bool
	public var published: Date?
	public var updated: Date?
	public var deleted: Bool
	public var apId: String
	public var local: Bool
	public var path: String
	public var distinguished: Bool
	public var languageId: Int

	public init(
		id: Int,
		creatorId: Int,
		postId: Int,
		content: String,
		removed: Bool,
		published: Date? = nil,
		updated: Date? = nil,
		deleted: Bool,
		apId: String,
		local: Bool,
		path: String,
		distinguished: Bool,
		languageId: Int
	) {
		self.id = id
		self.creatorId = creatorId
		self.postId = postId
		self.content = content
		self.removed = removed
		self.published = published
		self.updated = updated
		self.deleted = deleted
		self.apId = apId
		self.local = local
		self.path = path
		self.distinguished = distinguished
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case creatorId = "creator_id"
		case postId = "post_id"
		case content
		case removed
		case published
		case updated
		case deleted
		case apId = "ap_id"
		case local
		case path
		case distinguished
		case languageId = "language_id"
	}
}
