// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentReplyInsertForm.swift

import Foundation

public struct CommentReplyInsertForm: Codable {
	public var recipientId: Int
	public var commentId: Int
	public var read: Bool?

	public init(recipientId: Int, commentId: Int, read: Bool? = nil) {
		self.recipientId = recipientId
		self.commentId = commentId
		self.read = read
	}

	public enum CodingKeys: String, CodingKey {
		case recipientId = "recipient_id"
		case commentId = "comment_id"
		case read
	}
}
