// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityPersonBanView.swift

import Foundation

public struct CommunityPersonBanView: Codable {
	public var community: Community
	public var person: Person

	public init(community: Community, person: Person) {
		self.community = community
		self.person = person
	}

	public enum CodingKeys: String, CodingKey {
		case community
		case person
	}
}
