// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityLanguage.swift

import Foundation

public struct CommunityLanguage: Codable {
	public var id: Int
	public var communityId: Int
	public var languageId: Int

	public init(id: Int, communityId: Int, languageId: Int) {
		self.id = id
		self.communityId = communityId
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case communityId = "community_id"
		case languageId = "language_id"
	}
}
