// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentReplyView.swift

import Foundation

public struct CommentReplyView: Codable {
	public var commentReply: CommentReply
	public var comment: Comment
	public var creator: Person
	public var post: Post
	public var community: Community
	public var recipient: Person
	public var counts: CommentAggregates
	public var creatorBannedFromCommunity: Bool
	public var subscribed: SubscribedType
	public var saved: Bool
	public var creatorBlocked: Bool
	public var myVote: Int16?

	public init(
		commentReply: CommentReply,
		comment: Comment,
		creator: Person,
		post: Post,
		community: Community,
		recipient: Person,
		counts: CommentAggregates,
		creatorBannedFromCommunity: Bool,
		subscribed: SubscribedType,
		saved: Bool,
		creatorBlocked: Bool,
		myVote: Int16? = nil
	) {
		self.commentReply = commentReply
		self.comment = comment
		self.creator = creator
		self.post = post
		self.community = community
		self.recipient = recipient
		self.counts = counts
		self.creatorBannedFromCommunity = creatorBannedFromCommunity
		self.subscribed = subscribed
		self.saved = saved
		self.creatorBlocked = creatorBlocked
		self.myVote = myVote
	}

	public enum CodingKeys: String, CodingKey {
		case commentReply = "comment_reply"
		case comment
		case creator
		case post
		case community
		case recipient
		case counts
		case creatorBannedFromCommunity = "creator_banned_from_community"
		case subscribed
		case saved
		case creatorBlocked = "creator_blocked"
		case myVote = "my_vote"
	}
}
