// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentLike.swift

import Foundation

public struct CommentLike: Codable {
	public var id: Int32
	public var personId: Int
	public var commentId: Int
	public var postId: Int
	public var score: Int16
	public var published: Date?

	public init(
		id: Int32,
		personId: Int,
		commentId: Int,
		postId: Int,
		score: Int16,
		published: Date? = nil
	) {
		self.id = id
		self.personId = personId
		self.commentId = commentId
		self.postId = postId
		self.score = score
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case personId = "person_id"
		case commentId = "comment_id"
		case postId = "post_id"
		case score
		case published
	}
}
