// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentSortType.swift

import Foundation

public enum CommentSortType: String, Codable, CaseIterable {
	case hot = "Hot"
	case top = "Top"
	case new = "New"
	case old = "Old"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract CommentSortType from value \(value)"
			))
		}

		self = mode
	}
}
