// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityAggregates.swift

import Foundation

public struct CommunityAggregates: Codable {
	public var id: Int32
	public var communityId: Int
	public var subscribers: Int
	public var posts: Int
	public var comments: Int
	public var published: Date?
	public var usersActiveDay: Int
	public var usersActiveWeek: Int
	public var usersActiveMonth: Int
	public var usersActiveHalfYear: Int
	public var hotRank: Int32

	public init(
		id: Int32,
		communityId: Int,
		subscribers: Int,
		posts: Int,
		comments: Int,
		published: Date? = nil,
		usersActiveDay: Int,
		usersActiveWeek: Int,
		usersActiveMonth: Int,
		usersActiveHalfYear: Int,
		hotRank: Int32
	) {
		self.id = id
		self.communityId = communityId
		self.subscribers = subscribers
		self.posts = posts
		self.comments = comments
		self.published = published
		self.usersActiveDay = usersActiveDay
		self.usersActiveWeek = usersActiveWeek
		self.usersActiveMonth = usersActiveMonth
		self.usersActiveHalfYear = usersActiveHalfYear
		self.hotRank = hotRank
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case communityId = "community_id"
		case subscribers
		case posts
		case comments
		case published
		case usersActiveDay = "users_active_day"
		case usersActiveWeek = "users_active_week"
		case usersActiveMonth = "users_active_month"
		case usersActiveHalfYear = "users_active_half_year"
		case hotRank = "hot_rank"
	}
}
