// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentLikeForm.swift

import Foundation

public struct CommentLikeForm: Codable {
	public var personId: Int
	public var commentId: Int
	public var postId: Int
	public var score: Int16

	public init(personId: Int, commentId: Int, postId: Int, score: Int16) {
		self.personId = personId
		self.commentId = commentId
		self.postId = postId
		self.score = score
	}

	public enum CodingKeys: String, CodingKey {
		case personId = "person_id"
		case commentId = "comment_id"
		case postId = "post_id"
		case score
	}
}
