// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommunityLanguageForm.swift

import Foundation

public struct CommunityLanguageForm: Codable {
	public var communityId: Int
	public var languageId: Int

	public init(communityId: Int, languageId: Int) {
		self.communityId = communityId
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case languageId = "language_id"
	}
}
