// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentSaved.swift

import Foundation

public struct CommentSaved: Codable {
	public var id: Int32
	public var commentId: Int
	public var personId: Int
	public var published: Date?

	public init(id: Int32, commentId: Int, personId: Int, published: Date? = nil) {
		self.id = id
		self.commentId = commentId
		self.personId = personId
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case commentId = "comment_id"
		case personId = "person_id"
		case published
	}
}
