// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentUpdateForm.swift

import Foundation

public struct CommentUpdateForm: Codable {
	public var content: String?
	public var removed: Bool?
	public var updated: Date?
	public var deleted: Bool?
	public var apId: String?
	public var local: Bool?
	public var distinguished: Bool?
	public var languageId: Int?

	public init(
		content: String? = nil,
		removed: Bool? = nil,
		updated: Date? = nil,
		deleted: Bool? = nil,
		apId: String? = nil,
		local: Bool? = nil,
		distinguished: Bool? = nil,
		languageId: Int? = nil
	) {
		self.content = content
		self.removed = removed
		self.updated = updated
		self.deleted = deleted
		self.apId = apId
		self.local = local
		self.distinguished = distinguished
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case content
		case removed
		case updated
		case deleted
		case apId = "ap_id"
		case local
		case distinguished
		case languageId = "language_id"
	}
}
