// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CommentAggregates.swift

import Foundation

public struct CommentAggregates: Codable {
	public var id: Int32
	public var commentId: Int
	public var score: Int
	public var upvotes: Int
	public var downvotes: Int
	public var published: Date?
	public var childCount: Int32
	public var hotRank: Int32

	public init(
		id: Int32,
		commentId: Int,
		score: Int,
		upvotes: Int,
		downvotes: Int,
		published: Date? = nil,
		childCount: Int32,
		hotRank: Int32
	) {
		self.id = id
		self.commentId = commentId
		self.score = score
		self.upvotes = upvotes
		self.downvotes = downvotes
		self.published = published
		self.childCount = childCount
		self.hotRank = hotRank
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case commentId = "comment_id"
		case score
		case upvotes
		case downvotes
		case published
		case childCount = "child_count"
		case hotRank = "hot_rank"
	}
}
