// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmojiUpdateForm.swift

import Foundation

public struct CustomEmojiUpdateForm: Codable {
	public var localSiteId: Int
	public var imageURL: URL?
	public var altText: String
	public var category: String

	public init(localSiteId: Int, imageURL: URL? = nil, altText: String, category: String) {
		self.localSiteId = localSiteId
		self.imageURL = imageURL
		self.altText = altText
		self.category = category
	}

	public enum CodingKeys: String, CodingKey {
		case localSiteId = "local_site_id"
		case imageURL = "image_url"
		case altText = "alt_text"
		case category
	}
}
