// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmojiInsertForm.swift

import Foundation

public struct CustomEmojiInsertForm: Codable {
	public var localSiteId: Int
	public var shortcode: String
	public var imageUrl: URL?
	public var altText: String
	public var category: String

	public init(
		localSiteId: Int,
		shortcode: String,
		imageUrl: URL? = nil,
		altText: String,
		category: String
	) {
		self.localSiteId = localSiteId
		self.shortcode = shortcode
		self.imageUrl = imageUrl
		self.altText = altText
		self.category = category
	}

	public enum CodingKeys: String, CodingKey {
		case localSiteId = "local_site_id"
		case shortcode
		case imageUrl = "image_url"
		case altText = "alt_text"
		case category
	}
}
