// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmojiView.swift

import Foundation

public struct CustomEmojiView: Codable {
	public var customEmoji: CustomEmoji
	public var keywords: [CustomEmojiKeyword]

	public init(customEmoji: CustomEmoji, keywords: [CustomEmojiKeyword]) {
		self.customEmoji = customEmoji
		self.keywords = keywords
	}

	public enum CodingKeys: String, CodingKey {
		case customEmoji = "custom_emoji"
		case keywords
	}
}
