// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmojiKeyword.swift

import Foundation

public struct CustomEmojiKeyword: Codable {
	public var id: Int32
	public var customEmojiId: Int
	public var keyword: String

	public init(id: Int32, customEmojiId: Int, keyword: String) {
		self.id = id
		self.customEmojiId = customEmojiId
		self.keyword = keyword
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case customEmojiId = "custom_emoji_id"
		case keyword
	}
}
