// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmoji.swift

import Foundation

public struct CustomEmoji: Codable {
	public var id: Int
	public var localSiteId: Int
	public var shortcode: String
	public var imageUrl: URL?
	public var altText: String
	public var category: String
	public var published: Date?
	public var updated: Date?

	public init(
		id: Int,
		localSiteId: Int,
		shortcode: String,
		imageUrl: URL? = nil,
		altText: String,
		category: String,
		published: Date? = nil,
		updated: Date? = nil
	) {
		self.id = id
		self.localSiteId = localSiteId
		self.shortcode = shortcode
		self.imageUrl = imageUrl
		self.altText = altText
		self.category = category
		self.published = published
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case localSiteId = "local_site_id"
		case shortcode
		case imageUrl = "image_url"
		case altText = "alt_text"
		case category
		case published
		case updated
	}
}
