// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: CustomEmojiKeywordInsertForm.swift

import Foundation

public struct CustomEmojiKeywordInsertForm: Codable {
	public var customEmojiId: Int
	public var keyword: String

	public init(customEmojiId: Int, keyword: String) {
		self.customEmojiId = customEmojiId
		self.keyword = keyword
	}

	public enum CodingKeys: String, CodingKey {
		case customEmojiId = "custom_emoji_id"
		case keyword
	}
}
