// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeleteAccountResponse.swift

import Foundation

public struct DeleteAccountResponse: Codable {
	public var email: String

	public init(email: String) {
		self.email = email
	}

	public enum CodingKeys: String, CodingKey {
		case email
	}
}
