// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: DeleteCustomEmojiResponse.swift

import Foundation

public struct DeleteCustomEmojiResponse: Codable {
	public var id: Int
	public var success: Bool

	public init(id: Int, success: Bool) {
		self.id = id
		self.success = success
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case success
	}
}
