// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EmailVerificationForm.swift

import Foundation

public struct EmailVerificationForm: Codable {
	public var localUserId: Int
	public var email: String
	public var verificationToken: String

	public init(localUserId: Int, email: String, verificationToken: String) {
		self.localUserId = localUserId
		self.email = email
		self.verificationToken = verificationToken
	}

	public enum CodingKeys: String, CodingKey {
		case localUserId = "local_user_id"
		case email
		case verificationToken = "verification_token"
	}
}
