// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: EndpointType.swift

import Foundation

public enum EndpointType: String, Codable, CaseIterable, CustomStringConvertible {
	case community = "Community"
	case person = "Person"
	case post = "Post"
	case comment = "Comment"
	case privatemessage = "PrivateMessage"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract EndpointType from value \(value)"
			))
		}

		self = mode
	}
}
