// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetCommentsResponse.swift

import Foundation

public struct GetCommentsResponse: Codable {
	public var comments: [CommentView]

	public init(comments: [CommentView]) {
		self.comments = comments
	}

	public enum CodingKeys: String, CodingKey {
		case comments
	}
}
