// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetCommunityResponse.swift

import Foundation

public struct GetCommunityResponse: Codable {
	public var communityView: CommunityView
	public var site: Site?
	public var moderators: [CommunityModeratorView]
	public var discussionLanguages: [Int]

	public init(
		communityView: CommunityView,
		site: Site? = nil,
		moderators: [CommunityModeratorView],
		discussionLanguages: [Int]
	) {
		self.communityView = communityView
		self.site = site
		self.moderators = moderators
		self.discussionLanguages = discussionLanguages
	}

	public enum CodingKeys: String, CodingKey {
		case communityView = "community_view"
		case site
		case moderators
		case discussionLanguages = "discussion_languages"
	}
}
