// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetCaptchaResponse.swift

import Foundation

public struct GetCaptchaResponse: Codable {
	public var ok: CaptchaResponse?

	public init(ok: CaptchaResponse? = nil) {
		self.ok = ok
	}

	public enum CodingKeys: String, CodingKey {
		case ok
	}
}
