// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetFederatedInstancesResponse.swift

import Foundation

public struct GetFederatedInstancesResponse: Codable {
	public var federatedInstances: FederatedInstances?

	public init(federatedInstances: FederatedInstances? = nil) {
		self.federatedInstances = federatedInstances
	}

	public enum CodingKeys: String, CodingKey {
		case federatedInstances = "federated_instances"
	}
}
