// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetModlogResponse.swift

import Foundation

public struct GetModlogResponse: Codable {
	public var removedPosts: [ModRemovePostView]
	public var lockedPosts: [ModLockPostView]
	public var featuredPosts: [ModFeaturePostView]
	public var removedComments: [ModRemoveCommentView]
	public var removedCommunities: [ModRemoveCommunityView]
	public var bannedFromCommunity: [ModBanFromCommunityView]
	public var banned: [ModBanView]
	public var addedToCommunity: [ModAddCommunityView]
	public var transferredToCommunity: [ModTransferCommunityView]
	public var added: [ModAddView]
	public var adminPurgedPersons: [AdminPurgePersonView]
	public var adminPurgedCommunities: [AdminPurgeCommunityView]
	public var adminPurgedPosts: [AdminPurgePostView]
	public var adminPurgedComments: [AdminPurgeCommentView]
	public var hiddenCommunities: [ModHideCommunityView]

	public init(
		removedPosts: [ModRemovePostView],
		lockedPosts: [ModLockPostView],
		featuredPosts: [ModFeaturePostView],
		removedComments: [ModRemoveCommentView],
		removedCommunities: [ModRemoveCommunityView],
		bannedFromCommunity: [ModBanFromCommunityView],
		banned: [ModBanView],
		addedToCommunity: [ModAddCommunityView],
		transferredToCommunity: [ModTransferCommunityView],
		added: [ModAddView],
		adminPurgedPersons: [AdminPurgePersonView],
		adminPurgedCommunities: [AdminPurgeCommunityView],
		adminPurgedPosts: [AdminPurgePostView],
		adminPurgedComments: [AdminPurgeCommentView],
		hiddenCommunities: [ModHideCommunityView]
	) {
		self.removedPosts = removedPosts
		self.lockedPosts = lockedPosts
		self.featuredPosts = featuredPosts
		self.removedComments = removedComments
		self.removedCommunities = removedCommunities
		self.bannedFromCommunity = bannedFromCommunity
		self.banned = banned
		self.addedToCommunity = addedToCommunity
		self.transferredToCommunity = transferredToCommunity
		self.added = added
		self.adminPurgedPersons = adminPurgedPersons
		self.adminPurgedCommunities = adminPurgedCommunities
		self.adminPurgedPosts = adminPurgedPosts
		self.adminPurgedComments = adminPurgedComments
		self.hiddenCommunities = hiddenCommunities
	}

	public enum CodingKeys: String, CodingKey {
		case removedPosts = "removed_posts"
		case lockedPosts = "locked_posts"
		case featuredPosts = "featured_posts"
		case removedComments = "removed_comments"
		case removedCommunities = "removed_communities"
		case bannedFromCommunity = "banned_from_community"
		case banned
		case addedToCommunity = "added_to_community"
		case transferredToCommunity = "transferred_to_community"
		case added
		case adminPurgedPersons = "admin_purged_persons"
		case adminPurgedCommunities = "admin_purged_communities"
		case adminPurgedPosts = "admin_purged_posts"
		case adminPurgedComments = "admin_purged_comments"
		case hiddenCommunities = "hidden_communities"
	}
}
