// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetPostsResponse.swift

import Foundation

public struct GetPostsResponse: Codable {
	public var posts: [PostView]

	public init(posts: [PostView]) {
		self.posts = posts
	}

	public enum CodingKeys: String, CodingKey {
		case posts
	}
}
