// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetPersonDetailsResponse.swift

import Foundation

public struct GetPersonDetailsResponse: Codable {
	public var personView: PersonView
	public var comments: [CommentView]
	public var posts: [PostView]
	public var moderates: [CommunityModeratorView]

	public init(
		personView: PersonView,
		comments: [CommentView],
		posts: [PostView],
		moderates: [CommunityModeratorView]
	) {
		self.personView = personView
		self.comments = comments
		self.posts = posts
		self.moderates = moderates
	}

	public enum CodingKeys: String, CodingKey {
		case personView = "person_view"
		case comments
		case posts
		case moderates
	}
}
