// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetRepliesResponse.swift

import Foundation

public struct GetRepliesResponse: Codable {
	public var replies: [CommentReplyView]

	public init(replies: [CommentReplyView]) {
		self.replies = replies
	}

	public enum CodingKeys: String, CodingKey {
		case replies
	}
}
