// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetReportCountResponse.swift

import Foundation

public struct GetReportCountResponse: Codable {
	public var communityId: Int?
	public var commentReports: Int
	public var postReports: Int
	public var privateMessageReports: Int?

	public init(
		communityId: Int? = nil,
		commentReports: Int,
		postReports: Int,
		privateMessageReports: Int? = nil
	) {
		self.communityId = communityId
		self.commentReports = commentReports
		self.postReports = postReports
		self.privateMessageReports = privateMessageReports
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case commentReports = "comment_reports"
		case postReports = "post_reports"
		case privateMessageReports = "private_message_reports"
	}
}
