// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetSiteMetadataResponse.swift

import Foundation

public struct GetSiteMetadataResponse: Codable {
	public var metadata: SiteMetadata

	public init(metadata: SiteMetadata) {
		self.metadata = metadata
	}

	public enum CodingKeys: String, CodingKey {
		case metadata
	}
}
