// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetSiteResponse.swift

import Foundation

public struct GetSiteResponse: Codable {
	public var siteView: SiteView
	public var admins: [PersonView]
	public var version: String
	public var myUser: MyUserInfo?
	public var allLanguages: [Language]
	public var discussionLanguages: [Int]
	public var taglines: [Tagline]
	public var customEmojis: [CustomEmojiView]

	public init(
		siteView: SiteView,
		admins: [PersonView],
		version: String,
		myUser: MyUserInfo? = nil,
		allLanguages: [Language],
		discussionLanguages: [Int],
		taglines: [Tagline],
		customEmojis: [CustomEmojiView]
	) {
		self.siteView = siteView
		self.admins = admins
		self.version = version
		self.myUser = myUser
		self.allLanguages = allLanguages
		self.discussionLanguages = discussionLanguages
		self.taglines = taglines
		self.customEmojis = customEmojis
	}

	public enum CodingKeys: String, CodingKey {
		case siteView = "site_view"
		case admins
		case version
		case myUser = "my_user"
		case allLanguages = "all_languages"
		case discussionLanguages = "discussion_languages"
		case taglines
		case customEmojis = "custom_emojis"
	}
}
