// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetUnreadRegistrationApplicationCountResponse.swift

import Foundation

public struct GetUnreadRegistrationApplicationCountResponse: Codable {
	public var registrationApplications: Int

	public init(registrationApplications: Int) {
		self.registrationApplications = registrationApplications
	}

	public enum CodingKeys: String, CodingKey {
		case registrationApplications = "registration_applications"
	}
}
