// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: GetUnreadCountResponse.swift

import Foundation

public struct GetUnreadCountResponse: Codable {
	public var replies: Int
	public var mentions: Int
	public var privateMessages: Int

	public init(replies: Int, mentions: Int, privateMessages: Int) {
		self.replies = replies
		self.mentions = mentions
		self.privateMessages = privateMessages
	}

	public enum CodingKeys: String, CodingKey {
		case replies
		case mentions
		case privateMessages = "private_messages"
	}
}
