// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Instance.swift

import Foundation

public struct Instance: Codable {
	public var id: Int
	public var domain: String
	public var published: Date?
	public var updated: Date?
	public var software: String?
	public var version: String?

	public init(
		id: Int,
		domain: String,
		published: Date? = nil,
		updated: Date? = nil,
		software: String? = nil,
		version: String? = nil
	) {
		self.id = id
		self.domain = domain
		self.published = published
		self.updated = updated
		self.software = software
		self.version = version
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case domain
		case published
		case updated
		case software
		case version
	}
}
