// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Language.swift

import Foundation

public struct Language: Codable {
	public var id: Int
	public var code: String
	public var name: String

	public init(id: Int, code: String, name: String) {
		self.id = id
		self.code = code
		self.name = name
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case code
		case name
	}
}
