// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListCommentReportsResponse.swift

import Foundation

public struct ListCommentReportsResponse: Codable {
	public var commentReports: [CommentReportView]

	public init(commentReports: [CommentReportView]) {
		self.commentReports = commentReports
	}

	public enum CodingKeys: String, CodingKey {
		case commentReports = "comment_reports"
	}
}
