// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListingType.swift

import Foundation

public enum ListingType: String, Codable, CaseIterable {
	case all = "All"
	case local = "Local"
	case subscribed = "Subscribed"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract ListingType from value \(value)"
			))
		}

		self = mode
	}
}
