// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListPrivateMessageReportsResponse.swift

import Foundation

public struct ListPrivateMessageReportsResponse: Codable {
	public var privateMessageReports: [PrivateMessageReportView]

	public init(privateMessageReports: [PrivateMessageReportView]) {
		self.privateMessageReports = privateMessageReports
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessageReports = "private_message_reports"
	}
}
