// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListRegistrationApplicationsResponse.swift

import Foundation

public struct ListRegistrationApplicationsResponse: Codable {
	public var registrationApplications: [RegistrationApplicationView]

	public init(registrationApplications: [RegistrationApplicationView]) {
		self.registrationApplications = registrationApplications
	}

	public enum CodingKeys: String, CodingKey {
		case registrationApplications = "registration_applications"
	}
}
