// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListCommunitiesResponse.swift

import Foundation

public struct ListCommunitiesResponse: Codable {
	public var communities: [CommunityView]

	public init(communities: [CommunityView]) {
		self.communities = communities
	}

	public enum CodingKeys: String, CodingKey {
		case communities
	}
}
