// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ListPostReportsResponse.swift

import Foundation

public struct ListPostReportsResponse: Codable {
	public var postReports: [PostReportView]

	public init(postReports: [PostReportView]) {
		self.postReports = postReports
	}

	public enum CodingKeys: String, CodingKey {
		case postReports = "post_reports"
	}
}
