// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LocalSite.swift

import Foundation

public struct LocalSite: Codable {
	public var id: Int
	public var siteId: Int
	public var siteSetup: Bool
	public var enableDownvotes: Bool
	public var enableNSFW: Bool
	public var communityCreationAdminOnly: Bool
	public var requireEmailVerification: Bool
	public var applicationQuestion: String?
	public var privateInstance: Bool
	public var defaultTheme: String
	public var defaultPostListingType: ListingType
	public var legalInformation: String?
	public var hideModlogModNames: Bool
	public var applicationEmailAdmins: Bool
	public var slurFilterRegex: String?
	public var actorNameMaxLength: Int32
	public var federationEnabled: Bool
	public var captchaEnabled: Bool
	public var captchaDifficulty: String
	public var published: Date?
	public var updated: Date?
	public var registrationMode: RegistrationMode
	public var reportsEmailAdmins: Bool

	public init(
		id: Int,
		siteId: Int,
		siteSetup: Bool,
		enableDownvotes: Bool,
		enableNSFW: Bool,
		communityCreationAdminOnly: Bool,
		requireEmailVerification: Bool,
		applicationQuestion: String? = nil,
		privateInstance: Bool,
		defaultTheme: String,
		defaultPostListingType: ListingType,
		legalInformation: String? = nil,
		hideModlogModNames: Bool,
		applicationEmailAdmins: Bool,
		slurFilterRegex: String? = nil,
		actorNameMaxLength: Int32,
		federationEnabled: Bool,
		captchaEnabled: Bool,
		captchaDifficulty: String,
		published: Date? = nil,
		updated: Date? = nil,
		registrationMode: RegistrationMode,
		reportsEmailAdmins: Bool
	) {
		self.id = id
		self.siteId = siteId
		self.siteSetup = siteSetup
		self.enableDownvotes = enableDownvotes
		self.enableNSFW = enableNSFW
		self.communityCreationAdminOnly = communityCreationAdminOnly
		self.requireEmailVerification = requireEmailVerification
		self.applicationQuestion = applicationQuestion
		self.privateInstance = privateInstance
		self.defaultTheme = defaultTheme
		self.defaultPostListingType = defaultPostListingType
		self.legalInformation = legalInformation
		self.hideModlogModNames = hideModlogModNames
		self.applicationEmailAdmins = applicationEmailAdmins
		self.slurFilterRegex = slurFilterRegex
		self.actorNameMaxLength = actorNameMaxLength
		self.federationEnabled = federationEnabled
		self.captchaEnabled = captchaEnabled
		self.captchaDifficulty = captchaDifficulty
		self.published = published
		self.updated = updated
		self.registrationMode = registrationMode
		self.reportsEmailAdmins = reportsEmailAdmins
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case siteId = "site_id"
		case siteSetup = "site_setup"
		case enableDownvotes = "enable_downvotes"
		case enableNSFW = "enable_nsfw"
		case communityCreationAdminOnly = "community_creation_admin_only"
		case requireEmailVerification = "require_email_verification"
		case applicationQuestion = "application_question"
		case privateInstance = "private_instance"
		case defaultTheme = "default_theme"
		case defaultPostListingType = "default_post_listing_type"
		case legalInformation = "legal_information"
		case hideModlogModNames = "hide_modlog_mod_names"
		case applicationEmailAdmins = "application_email_admins"
		case slurFilterRegex = "slur_filter_regex"
		case actorNameMaxLength = "actor_name_max_length"
		case federationEnabled = "federation_enabled"
		case captchaEnabled = "captcha_enabled"
		case captchaDifficulty = "captcha_difficulty"
		case published
		case updated
		case registrationMode = "registration_mode"
		case reportsEmailAdmins = "reports_email_admins"
	}
}
