// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LocalSiteRateLimitUpdateForm.swift

import Foundation

public struct LocalSiteRateLimitUpdateForm: Codable {
	public var message: Int32?
	public var messagePerSecond: Int32?
	public var post: Int32?
	public var postPerSecond: Int32?
	public var register: Int32?
	public var registerPerSecond: Int32?
	public var image: Int32?
	public var imagePerSecond: Int32?
	public var comment: Int32?
	public var commentPerSecond: Int32?
	public var search: Int32?
	public var searchPerSecond: Int32?
	public var updated: Date?

	public init(
		message: Int32? = nil,
		messagePerSecond: Int32? = nil,
		post: Int32? = nil,
		postPerSecond: Int32? = nil,
		register: Int32? = nil,
		registerPerSecond: Int32? = nil,
		image: Int32? = nil,
		imagePerSecond: Int32? = nil,
		comment: Int32? = nil,
		commentPerSecond: Int32? = nil,
		search: Int32? = nil,
		searchPerSecond: Int32? = nil,
		updated: Date? = nil
	) {
		self.message = message
		self.messagePerSecond = messagePerSecond
		self.post = post
		self.postPerSecond = postPerSecond
		self.register = register
		self.registerPerSecond = registerPerSecond
		self.image = image
		self.imagePerSecond = imagePerSecond
		self.comment = comment
		self.commentPerSecond = commentPerSecond
		self.search = search
		self.searchPerSecond = searchPerSecond
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case message
		case messagePerSecond = "message_per_second"
		case post
		case postPerSecond = "post_per_second"
		case register
		case registerPerSecond = "register_per_second"
		case image
		case imagePerSecond = "image_per_second"
		case comment
		case commentPerSecond = "comment_per_second"
		case search
		case searchPerSecond = "search_per_second"
		case updated
	}
}
