// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LocalUserView.swift

import Foundation

public struct LocalUserView: Codable {
	public var localUser: LocalUser
	public var person: Person
	public var counts: PersonAggregates

	public init(localUser: LocalUser, person: Person, counts: PersonAggregates) {
		self.localUser = localUser
		self.person = person
		self.counts = counts
	}

	public enum CodingKeys: String, CodingKey {
		case localUser = "local_user"
		case person
		case counts
	}
}
