// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LocalUserUpdateForm.swift

import Foundation

public struct LocalUserUpdateForm: Codable {
	public var passwordEncrypted: String?
	public var email: String??
	public var showNSFW: Bool?
	public var theme: String?
	public var defaultSortType: SortType?
	public var defaultListingType: ListingType?
	public var interfaceLanguage: String?
	public var showAvatars: Bool?
	public var sendNotificationsToEmail: Bool?
	public var showBotAccounts: Bool?
	public var showScores: Bool?
	public var showReadPosts: Bool?
	public var showNewPostNotifs: Bool?
	public var emailVerified: Bool?
	public var acceptedApplication: Bool?
	public var totp2faSecret: String??
	public var totp2faUrl: URL?

	public init(
		passwordEncrypted: String? = nil,
		email: String?? = nil,
		showNSFW: Bool? = nil,
		theme: String? = nil,
		defaultSortType: SortType? = nil,
		defaultListingType: ListingType? = nil,
		interfaceLanguage: String? = nil,
		showAvatars: Bool? = nil,
		sendNotificationsToEmail: Bool? = nil,
		showBotAccounts: Bool? = nil,
		showScores: Bool? = nil,
		showReadPosts: Bool? = nil,
		showNewPostNotifs: Bool? = nil,
		emailVerified: Bool? = nil,
		acceptedApplication: Bool? = nil,
		totp2faSecret: String?? = nil,
		totp2faUrl: URL? = nil
	) {
		self.passwordEncrypted = passwordEncrypted
		self.email = email
		self.showNSFW = showNSFW
		self.theme = theme
		self.defaultSortType = defaultSortType
		self.defaultListingType = defaultListingType
		self.interfaceLanguage = interfaceLanguage
		self.showAvatars = showAvatars
		self.sendNotificationsToEmail = sendNotificationsToEmail
		self.showBotAccounts = showBotAccounts
		self.showScores = showScores
		self.showReadPosts = showReadPosts
		self.showNewPostNotifs = showNewPostNotifs
		self.emailVerified = emailVerified
		self.acceptedApplication = acceptedApplication
		self.totp2faSecret = totp2faSecret
		self.totp2faUrl = totp2faUrl
	}

	public enum CodingKeys: String, CodingKey {
		case passwordEncrypted = "password_encrypted"
		case email
		case showNSFW = "show_nsfw"
		case theme
		case defaultSortType = "default_sort_type"
		case defaultListingType = "default_listing_type"
		case interfaceLanguage = "interface_language"
		case showAvatars = "show_avatars"
		case sendNotificationsToEmail = "send_notifications_to_email"
		case showBotAccounts = "show_bot_accounts"
		case showScores = "show_scores"
		case showReadPosts = "show_read_posts"
		case showNewPostNotifs = "show_new_post_notifs"
		case emailVerified = "email_verified"
		case acceptedApplication = "accepted_application"
		case totp2faSecret = "totp_2fa_secret"
		case totp2faUrl = "totp_2fa_url"
	}
}
