// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LocalUserLanguage.swift

import Foundation

public struct LocalUserLanguage: Codable {
	public var id: Int
	public var localUserId: Int
	public var languageId: Int

	public init(id: Int, localUserId: Int, languageId: Int) {
		self.id = id
		self.localUserId = localUserId
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case localUserId = "local_user_id"
		case languageId = "language_id"
	}
}
