// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: LoginResponse.swift

import Foundation

public struct LoginResponse: Codable {
	public var jwt: String?
	public var registrationCreated: Bool
	public var verifyEmailSent: Bool

	public init(jwt: String? = nil, registrationCreated: Bool, verifyEmailSent: Bool) {
		self.jwt = jwt
		self.registrationCreated = registrationCreated
		self.verifyEmailSent = verifyEmailSent
	}

	public enum CodingKeys: String, CodingKey {
		case jwt
		case registrationCreated = "registration_created"
		case verifyEmailSent = "verify_email_sent"
	}
}
