// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModAddCommunityForm.swift

import Foundation

public struct ModAddCommunityForm: Codable {
	public var modPersonId: Int
	public var otherPersonId: Int
	public var communityId: Int
	public var removed: Bool?

	public init(modPersonId: Int, otherPersonId: Int, communityId: Int, removed: Bool? = nil) {
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.communityId = communityId
		self.removed = removed
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case communityId = "community_id"
		case removed
	}
}
