// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModAddCommunityView.swift

import Foundation

public struct ModAddCommunityView: Codable {
	public var modAddCommunity: ModAddCommunity
	public var moderator: Person?
	public var community: Community
	public var moddedPerson: Person

	public init(
		modAddCommunity: ModAddCommunity,
		moderator: Person? = nil,
		community: Community,
		moddedPerson: Person
	) {
		self.modAddCommunity = modAddCommunity
		self.moderator = moderator
		self.community = community
		self.moddedPerson = moddedPerson
	}

	public enum CodingKeys: String, CodingKey {
		case modAddCommunity = "mod_add_community"
		case moderator
		case community
		case moddedPerson = "modded_person"
	}
}
