// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModAddCommunity.swift

import Foundation

public struct ModAddCommunity: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var otherPersonId: Int
	public var communityId: Int
	public var removed: Bool
	public var when: Date?

	public init(
		id: Int32,
		modPersonId: Int,
		otherPersonId: Int,
		communityId: Int,
		removed: Bool,
		when: Date? = nil
	) {
		self.id = id
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.communityId = communityId
		self.removed = removed
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case communityId = "community_id"
		case removed
		case when = "when_"
	}
}
