// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModAdd.swift

import Foundation

public struct ModAdd: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var otherPersonId: Int
	public var removed: Bool
	public var when: Date?

	public init(id: Int32, modPersonId: Int, otherPersonId: Int, removed: Bool, when: Date? = nil) {
		self.id = id
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.removed = removed
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case removed
		case when = "when_"
	}
}
