// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModAddView.swift

import Foundation

public struct ModAddView: Codable {
	public var modAdd: ModAdd
	public var moderator: Person?
	public var moddedPerson: Person

	public init(modAdd: ModAdd, moderator: Person? = nil, moddedPerson: Person) {
		self.modAdd = modAdd
		self.moderator = moderator
		self.moddedPerson = moddedPerson
	}

	public enum CodingKeys: String, CodingKey {
		case modAdd = "mod_add"
		case moderator
		case moddedPerson = "modded_person"
	}
}
