// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModBanFromCommunityView.swift

import Foundation

public struct ModBanFromCommunityView: Codable {
	public var modBanFromCommunity: ModBanFromCommunity
	public var moderator: Person?
	public var community: Community
	public var bannedPerson: Person

	public init(
		modBanFromCommunity: ModBanFromCommunity,
		moderator: Person? = nil,
		community: Community,
		bannedPerson: Person
	) {
		self.modBanFromCommunity = modBanFromCommunity
		self.moderator = moderator
		self.community = community
		self.bannedPerson = bannedPerson
	}

	public enum CodingKeys: String, CodingKey {
		case modBanFromCommunity = "mod_ban_from_community"
		case moderator
		case community
		case bannedPerson = "banned_person"
	}
}
