// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModBanView.swift

import Foundation

public struct ModBanView: Codable {
	public var modBan: ModBan
	public var moderator: Person?
	public var bannedPerson: Person

	public init(modBan: ModBan, moderator: Person? = nil, bannedPerson: Person) {
		self.modBan = modBan
		self.moderator = moderator
		self.bannedPerson = bannedPerson
	}

	public enum CodingKeys: String, CodingKey {
		case modBan = "mod_ban"
		case moderator
		case bannedPerson = "banned_person"
	}
}
