// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModBanFromCommunityForm.swift

import Foundation

public struct ModBanFromCommunityForm: Codable {
	public var modPersonId: Int
	public var otherPersonId: Int
	public var communityId: Int
	public var reason: String?
	public var banned: Bool?
	public var expires: Date?

	public init(
		modPersonId: Int,
		otherPersonId: Int,
		communityId: Int,
		reason: String? = nil,
		banned: Bool? = nil,
		expires: Date? = nil
	) {
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.communityId = communityId
		self.reason = reason
		self.banned = banned
		self.expires = expires
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case communityId = "community_id"
		case reason
		case banned
		case expires
	}
}
