// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModBan.swift

import Foundation

public struct ModBan: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var otherPersonId: Int
	public var reason: String?
	public var banned: Bool
	public var expires: Date?
	public var when: Date?

	public init(
		id: Int32,
		modPersonId: Int,
		otherPersonId: Int,
		reason: String? = nil,
		banned: Bool,
		expires: Date? = nil,
		when: Date? = nil
	) {
		self.id = id
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.reason = reason
		self.banned = banned
		self.expires = expires
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case reason
		case banned
		case expires
		case when = "when_"
	}
}
