// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModFeaturePost.swift

import Foundation

public struct ModFeaturePost: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var postId: Int
	public var featured: Bool
	public var when: Date?
	public var isFeaturedCommunity: Bool

	public init(
		id: Int32,
		modPersonId: Int,
		postId: Int,
		featured: Bool,
		when: Date? = nil,
		isFeaturedCommunity: Bool
	) {
		self.id = id
		self.modPersonId = modPersonId
		self.postId = postId
		self.featured = featured
		self.when = when
		self.isFeaturedCommunity = isFeaturedCommunity
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case postId = "post_id"
		case featured
		case when = "when_"
		case isFeaturedCommunity = "is_featured_community"
	}
}
