// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModFeaturePostForm.swift

import Foundation

public struct ModFeaturePostForm: Codable {
	public var modPersonId: Int
	public var postId: Int
	public var featured: Bool
	public var isFeaturedCommunity: Bool

	public init(modPersonId: Int, postId: Int, featured: Bool, isFeaturedCommunity: Bool) {
		self.modPersonId = modPersonId
		self.postId = postId
		self.featured = featured
		self.isFeaturedCommunity = isFeaturedCommunity
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case postId = "post_id"
		case featured
		case isFeaturedCommunity = "is_featured_community"
	}
}
