// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModHideCommunity.swift

import Foundation

public struct ModHideCommunity: Codable {
	public var id: Int32
	public var communityId: Int
	public var modPersonId: Int
	public var when: Date?
	public var reason: String?
	public var hidden: Bool

	public init(
		id: Int32,
		communityId: Int,
		modPersonId: Int,
		when: Date? = nil,
		reason: String? = nil,
		hidden: Bool
	) {
		self.id = id
		self.communityId = communityId
		self.modPersonId = modPersonId
		self.when = when
		self.reason = reason
		self.hidden = hidden
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case communityId = "community_id"
		case modPersonId = "mod_person_id"
		case when = "when_"
		case reason
		case hidden
	}
}
