// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModHideCommunityForm.swift

import Foundation

public struct ModHideCommunityForm: Codable {
	public var communityId: Int
	public var modPersonId: Int
	public var hidden: Bool?
	public var reason: String?

	public init(communityId: Int, modPersonId: Int, hidden: Bool? = nil, reason: String? = nil) {
		self.communityId = communityId
		self.modPersonId = modPersonId
		self.hidden = hidden
		self.reason = reason
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case modPersonId = "mod_person_id"
		case hidden
		case reason
	}
}
