// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModLockPostForm.swift

import Foundation

public struct ModLockPostForm: Codable {
	public var modPersonId: Int
	public var postId: Int
	public var locked: Bool?

	public init(modPersonId: Int, postId: Int, locked: Bool? = nil) {
		self.modPersonId = modPersonId
		self.postId = postId
		self.locked = locked
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case postId = "post_id"
		case locked
	}
}
