// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModLockPostView.swift

import Foundation

public struct ModLockPostView: Codable {
	public var modLockPost: ModLockPost
	public var moderator: Person?
	public var post: Post
	public var community: Community

	public init(modLockPost: ModLockPost, moderator: Person? = nil, post: Post, community: Community) {
		self.modLockPost = modLockPost
		self.moderator = moderator
		self.post = post
		self.community = community
	}

	public enum CodingKeys: String, CodingKey {
		case modLockPost = "mod_lock_post"
		case moderator
		case post
		case community
	}
}
