// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModlogActionType.swift

import Foundation

public enum ModlogActionType: String, Codable, CaseIterable, CustomStringConvertible {
	case all = "All"
	case modremovepost = "ModRemovePost"
	case modlockpost = "ModLockPost"
	case modfeaturepost = "ModFeaturePost"
	case modremovecomment = "ModRemoveComment"
	case modremovecommunity = "ModRemoveCommunity"
	case modbanfromcommunity = "ModBanFromCommunity"
	case modaddcommunity = "ModAddCommunity"
	case modtransfercommunity = "ModTransferCommunity"
	case modadd = "ModAdd"
	case modban = "ModBan"
	case modhidecommunity = "ModHideCommunity"
	case adminpurgeperson = "AdminPurgePerson"
	case adminpurgecommunity = "AdminPurgeCommunity"
	case adminpurgepost = "AdminPurgePost"
	case adminpurgecomment = "AdminPurgeComment"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract ModlogActionType from value \(value)"
			))
		}

		self = mode
	}
}
