// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModlogListParams.swift

import Foundation

public struct ModlogListParams: Codable {
	public var communityId: Int?
	public var modPersonId: Int?
	public var otherPersonId: Int?
	public var page: Int?
	public var limit: Int?
	public var hideModlogNames: Bool

	public init(
		communityId: Int? = nil,
		modPersonId: Int? = nil,
		otherPersonId: Int? = nil,
		page: Int? = nil,
		limit: Int? = nil,
		hideModlogNames: Bool
	) {
		self.communityId = communityId
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.page = page
		self.limit = limit
		self.hideModlogNames = hideModlogNames
	}

	public enum CodingKeys: String, CodingKey {
		case communityId = "community_id"
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case page
		case limit
		case hideModlogNames = "hide_modlog_names"
	}
}
