// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModRemoveCommentView.swift

import Foundation

public struct ModRemoveCommentView: Codable {
	public var modRemoveComment: ModRemoveComment
	public var moderator: Person?
	public var comment: Comment
	public var commenter: Person
	public var post: Post
	public var community: Community

	public init(
		modRemoveComment: ModRemoveComment,
		moderator: Person? = nil,
		comment: Comment,
		commenter: Person,
		post: Post,
		community: Community
	) {
		self.modRemoveComment = modRemoveComment
		self.moderator = moderator
		self.comment = comment
		self.commenter = commenter
		self.post = post
		self.community = community
	}

	public enum CodingKeys: String, CodingKey {
		case modRemoveComment = "mod_remove_comment"
		case moderator
		case comment
		case commenter
		case post
		case community
	}
}
