// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModRemoveCommunityView.swift

import Foundation

public struct ModRemoveCommunityView: Codable {
	public var modRemoveCommunity: ModRemoveCommunity
	public var moderator: Person?
	public var community: Community

	public init(
		modRemoveCommunity: ModRemoveCommunity,
		moderator: Person? = nil,
		community: Community
	) {
		self.modRemoveCommunity = modRemoveCommunity
		self.moderator = moderator
		self.community = community
	}

	public enum CodingKeys: String, CodingKey {
		case modRemoveCommunity = "mod_remove_community"
		case moderator
		case community
	}
}
