// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModRemoveCommentForm.swift

import Foundation

public struct ModRemoveCommentForm: Codable {
	public var modPersonId: Int
	public var commentId: Int
	public var reason: String?
	public var removed: Bool?

	public init(modPersonId: Int, commentId: Int, reason: String? = nil, removed: Bool? = nil) {
		self.modPersonId = modPersonId
		self.commentId = commentId
		self.reason = reason
		self.removed = removed
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case commentId = "comment_id"
		case reason
		case removed
	}
}
