// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModRemoveComment.swift

import Foundation

public struct ModRemoveComment: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var commentId: Int
	public var reason: String?
	public var removed: Bool
	public var when: Date?

	public init(
		id: Int32,
		modPersonId: Int,
		commentId: Int,
		reason: String? = nil,
		removed: Bool,
		when: Date? = nil
	) {
		self.id = id
		self.modPersonId = modPersonId
		self.commentId = commentId
		self.reason = reason
		self.removed = removed
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case commentId = "comment_id"
		case reason
		case removed
		case when = "when_"
	}
}
