// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModTransferCommunityForm.swift

import Foundation

public struct ModTransferCommunityForm: Codable {
	public var modPersonId: Int
	public var otherPersonId: Int
	public var communityId: Int

	public init(modPersonId: Int, otherPersonId: Int, communityId: Int) {
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.communityId = communityId
	}

	public enum CodingKeys: String, CodingKey {
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case communityId = "community_id"
	}
}
