// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModTransferCommunity.swift

import Foundation

public struct ModTransferCommunity: Codable {
	public var id: Int32
	public var modPersonId: Int
	public var otherPersonId: Int
	public var communityId: Int
	public var when: Date?

	public init(id: Int32, modPersonId: Int, otherPersonId: Int, communityId: Int, when: Date? = nil) {
		self.id = id
		self.modPersonId = modPersonId
		self.otherPersonId = otherPersonId
		self.communityId = communityId
		self.when = when
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case modPersonId = "mod_person_id"
		case otherPersonId = "other_person_id"
		case communityId = "community_id"
		case when = "when_"
	}
}
