// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ModTransferCommunityView.swift

import Foundation

public struct ModTransferCommunityView: Codable {
	public var modTransferCommunity: ModTransferCommunity
	public var moderator: Person?
	public var community: Community
	public var moddedPerson: Person

	public init(
		modTransferCommunity: ModTransferCommunity,
		moderator: Person? = nil,
		community: Community,
		moddedPerson: Person
	) {
		self.modTransferCommunity = modTransferCommunity
		self.moderator = moderator
		self.community = community
		self.moddedPerson = moddedPerson
	}

	public enum CodingKeys: String, CodingKey {
		case modTransferCommunity = "mod_transfer_community"
		case moderator
		case community
		case moddedPerson = "modded_person"
	}
}
