// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PasswordResetResponse.swift

import Foundation

public struct PasswordResetResponse: Codable {
	public var token: String
	public var password: String
	public var passwordVerify: String

	public init(token: String, password: String, passwordVerify: String) {
		self.token = token
		self.password = password
		self.passwordVerify = passwordVerify
	}

	public enum CodingKeys: String, CodingKey {
		case token
		case password
		case passwordVerify = "password_verify"
	}
}
