// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PasswordResetRequest.swift

import Foundation

public struct PasswordResetRequest: Codable {
	public var id: Int32
	public var tokenEncrypted: String
	public var published: Date?
	public var localUserId: Int

	public init(id: Int32, tokenEncrypted: String, published: Date? = nil, localUserId: Int) {
		self.id = id
		self.tokenEncrypted = tokenEncrypted
		self.published = published
		self.localUserId = localUserId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case tokenEncrypted = "token_encrypted"
		case published
		case localUserId = "local_user_id"
	}
}
