// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonUpdateForm.swift

import Foundation

public struct PersonUpdateForm: Codable {
	public var displayName: String??
	public var avatar: String??
	public var banned: Bool?
	public var updated: Date?
	public var actorId: String?
	public var bio: String??
	public var local: Bool?
	public var publicKey: String?
	public var privateKey: String??
	public var lastRefreshedAt: Date?
	public var banner: String??
	public var deleted: Bool?
	public var inboxUrl: URL?
	public var sharedInboxUrl: URL?
	public var matrixUserId: String??
	public var admin: Bool?
	public var botAccount: Bool?
	public var banExpires: Date?

	public init(
		displayName: String?? = nil,
		avatar: String?? = nil,
		banned: Bool? = nil,
		updated: Date? = nil,
		actorId: String? = nil,
		bio: String?? = nil,
		local: Bool? = nil,
		publicKey: String? = nil,
		privateKey: String?? = nil,
		lastRefreshedAt: Date? = nil,
		banner: String?? = nil,
		deleted: Bool? = nil,
		inboxUrl: URL? = nil,
		sharedInboxUrl: URL? = nil,
		matrixUserId: String?? = nil,
		admin: Bool? = nil,
		botAccount: Bool? = nil,
		banExpires: Date? = nil
	) {
		self.displayName = displayName
		self.avatar = avatar
		self.banned = banned
		self.updated = updated
		self.actorId = actorId
		self.bio = bio
		self.local = local
		self.publicKey = publicKey
		self.privateKey = privateKey
		self.lastRefreshedAt = lastRefreshedAt
		self.banner = banner
		self.deleted = deleted
		self.inboxUrl = inboxUrl
		self.sharedInboxUrl = sharedInboxUrl
		self.matrixUserId = matrixUserId
		self.admin = admin
		self.botAccount = botAccount
		self.banExpires = banExpires
	}

	public enum CodingKeys: String, CodingKey {
		case displayName = "display_name"
		case avatar
		case banned
		case updated
		case actorId = "actor_id"
		case bio
		case local
		case publicKey = "public_key"
		case privateKey = "private_key"
		case lastRefreshedAt = "last_refreshed_at"
		case banner
		case deleted
		case inboxUrl = "inbox_url"
		case sharedInboxUrl = "shared_inbox_url"
		case matrixUserId = "matrix_user_id"
		case admin
		case botAccount = "bot_account"
		case banExpires = "ban_expires"
	}
}
