// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonFollower.swift

import Foundation

public struct PersonFollower: Codable {
	public var id: Int32
	public var personId: Int
	public var followerId: Int
	public var published: Date?
	public var pending: Bool

	public init(id: Int32, personId: Int, followerId: Int, published: Date? = nil, pending: Bool) {
		self.id = id
		self.personId = personId
		self.followerId = followerId
		self.published = published
		self.pending = pending
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case personId = "person_id"
		case followerId = "follower_id"
		case published
		case pending
	}
}
