// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonMentionResponse.swift

import Foundation

public struct PersonMentionResponse: Codable {
	public var personMentionView: PersonMentionView

	public init(personMentionView: PersonMentionView) {
		self.personMentionView = personMentionView
	}

	public enum CodingKeys: String, CodingKey {
		case personMentionView = "person_mention_view"
	}
}
