// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonBlock.swift

import Foundation

public struct PersonBlock: Codable {
	public var id: Int
	public var personId: Int
	public var targetId: Int
	public var published: Date?

	public init(id: Int, personId: Int, targetId: Int, published: Date? = nil) {
		self.id = id
		self.personId = personId
		self.targetId = targetId
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case personId = "person_id"
		case targetId = "target_id"
		case published
	}
}
