// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Person.swift

import Foundation

public struct Person: Codable {
	public var id: Int
	public var name: String
	public var displayName: String?
	public var avatar: String?
	public var banned: Bool
	public var published: Date?
	public var updated: Date?
	public var actorId: String
	public var bio: String?
	public var local: Bool
	public var privateKey: String?
	public var publicKey: String?
	public var lastRefreshedAt: Date?
	public var banner: String?
	public var deleted: Bool
	public var inboxUrl: URL?
	public var sharedInboxUrl: URL?
	public var matrixUserId: String?
	public var admin: Bool
	public var botAccount: Bool
	public var banExpires: Date?
	public var instanceId: Int

	public init(
		id: Int,
		name: String,
		displayName: String? = nil,
		avatar: String? = nil,
		banned: Bool,
		published: Date? = nil,
		updated: Date? = nil,
		actorId: String,
		bio: String? = nil,
		local: Bool,
		privateKey: String? = nil,
		publicKey: String? = nil,
		lastRefreshedAt: Date? = nil,
		banner: String? = nil,
		deleted: Bool,
		inboxUrl: URL? = nil,
		sharedInboxUrl: URL? = nil,
		matrixUserId: String? = nil,
		admin: Bool,
		botAccount: Bool,
		banExpires: Date? = nil,
		instanceId: Int
	) {
		self.id = id
		self.name = name
		self.displayName = displayName
		self.avatar = avatar
		self.banned = banned
		self.published = published
		self.updated = updated
		self.actorId = actorId
		self.bio = bio
		self.local = local
		self.privateKey = privateKey
		self.publicKey = publicKey
		self.lastRefreshedAt = lastRefreshedAt
		self.banner = banner
		self.deleted = deleted
		self.inboxUrl = inboxUrl
		self.sharedInboxUrl = sharedInboxUrl
		self.matrixUserId = matrixUserId
		self.admin = admin
		self.botAccount = botAccount
		self.banExpires = banExpires
		self.instanceId = instanceId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case name
		case displayName = "display_name"
		case avatar
		case banned
		case published
		case updated
		case actorId = "actor_id"
		case bio
		case local
		case privateKey = "private_key"
		case publicKey = "public_key"
		case lastRefreshedAt = "last_refreshed_at"
		case banner
		case deleted
		case inboxUrl = "inbox_url"
		case sharedInboxUrl = "shared_inbox_url"
		case matrixUserId = "matrix_user_id"
		case admin
		case botAccount = "bot_account"
		case banExpires = "ban_expires"
		case instanceId = "instance_id"
	}
}
