// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonBlockView.swift

import Foundation

public struct PersonBlockView: Codable {
	public var person: Person
	public var target: Person

	public init(person: Person, target: Person) {
		self.person = person
		self.target = target
	}

	public enum CodingKeys: String, CodingKey {
		case person
		case target
	}
}
