// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonFollowerForm.swift

import Foundation

public struct PersonFollowerForm: Codable {
	public var personId: Int
	public var followerId: Int
	public var pending: Bool

	public init(personId: Int, followerId: Int, pending: Bool) {
		self.personId = personId
		self.followerId = followerId
		self.pending = pending
	}

	public enum CodingKeys: String, CodingKey {
		case personId = "person_id"
		case followerId = "follower_id"
		case pending
	}
}
