// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonInsertForm.swift

import Foundation

public struct PersonInsertForm: Codable {
	public var name: String
	public var publicKey: String?
	public var instanceId: Int
	public var displayName: String?
	public var avatar: String?
	public var banned: Bool?
	public var published: Date?
	public var updated: Date?
	public var actorId: String?
	public var bio: String?
	public var local: Bool?
	public var privateKey: String?
	public var lastRefreshedAt: Date?
	public var banner: String?
	public var deleted: Bool?
	public var inboxURL: URL?
	public var sharedInboxURL: URL?
	public var matrixUserId: String?
	public var admin: Bool?
	public var botAccount: Bool?
	public var banExpires: Date?

	public init(
		name: String,
		publicKey: String? = nil,
		instanceId: Int,
		displayName: String? = nil,
		avatar: String? = nil,
		banned: Bool? = nil,
		published: Date? = nil,
		updated: Date? = nil,
		actorId: String? = nil,
		bio: String? = nil,
		local: Bool? = nil,
		privateKey: String? = nil,
		lastRefreshedAt: Date? = nil,
		banner: String? = nil,
		deleted: Bool? = nil,
		inboxURL: URL? = nil,
		sharedInboxURL: URL? = nil,
		matrixUserId: String? = nil,
		admin: Bool? = nil,
		botAccount: Bool? = nil,
		banExpires: Date? = nil
	) {
		self.name = name
		self.publicKey = publicKey
		self.instanceId = instanceId
		self.displayName = displayName
		self.avatar = avatar
		self.banned = banned
		self.published = published
		self.updated = updated
		self.actorId = actorId
		self.bio = bio
		self.local = local
		self.privateKey = privateKey
		self.lastRefreshedAt = lastRefreshedAt
		self.banner = banner
		self.deleted = deleted
		self.inboxURL = inboxURL
		self.sharedInboxURL = sharedInboxURL
		self.matrixUserId = matrixUserId
		self.admin = admin
		self.botAccount = botAccount
		self.banExpires = banExpires
	}

	public enum CodingKeys: String, CodingKey {
		case name
		case publicKey = "public_key"
		case instanceId = "instance_id"
		case displayName = "display_name"
		case avatar
		case banned
		case published
		case updated
		case actorId = "actor_id"
		case bio
		case local
		case privateKey = "private_key"
		case lastRefreshedAt = "last_refreshed_at"
		case banner
		case deleted
		case inboxURL = "inbox_url"
		case sharedInboxURL = "shared_inbox_url"
		case matrixUserId = "matrix_user_id"
		case admin
		case botAccount = "bot_account"
		case banExpires = "ban_expires"
	}
}
