// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonView.swift

import Foundation

public struct PersonView: Codable {
	public var person: Person
	public var counts: PersonAggregates

	public init(person: Person, counts: PersonAggregates) {
		self.person = person
		self.counts = counts
	}

	public enum CodingKeys: String, CodingKey {
		case person
		case counts
	}
}
