// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonPostAggregates.swift

import Foundation

public struct PersonPostAggregates: Codable {
	public var id: Int32
	public var personId: Int
	public var postId: Int
	public var readComments: Int
	public var published: Date?

	public init(id: Int32, personId: Int, postId: Int, readComments: Int, published: Date? = nil) {
		self.id = id
		self.personId = personId
		self.postId = postId
		self.readComments = readComments
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case personId = "person_id"
		case postId = "post_id"
		case readComments = "read_comments"
		case published
	}
}
