// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PersonMentionUpdateForm.swift

import Foundation

public struct PersonMentionUpdateForm: Codable {
	public var read: Bool?

	public init(read: Bool? = nil) {
		self.read = read
	}

	public enum CodingKeys: String, CodingKey {
		case read
	}
}
