// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostReport.swift

import Foundation

public struct PostReport: Codable {
	public var id: Int
	public var creatorId: Int
	public var postId: Int
	public var originalPostName: String
	public var originalPostUrl: URL?
	public var originalPostBody: String?
	public var reason: String
	public var resolved: Bool
	public var resolverId: Int?
	public var published: Date?
	public var updated: Date?

	public init(
		id: Int,
		creatorId: Int,
		postId: Int,
		originalPostName: String,
		originalPostUrl: URL? = nil,
		originalPostBody: String? = nil,
		reason: String,
		resolved: Bool,
		resolverId: Int? = nil,
		published: Date? = nil,
		updated: Date? = nil
	) {
		self.id = id
		self.creatorId = creatorId
		self.postId = postId
		self.originalPostName = originalPostName
		self.originalPostUrl = originalPostUrl
		self.originalPostBody = originalPostBody
		self.reason = reason
		self.resolved = resolved
		self.resolverId = resolverId
		self.published = published
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case creatorId = "creator_id"
		case postId = "post_id"
		case originalPostName = "original_post_name"
		case originalPostUrl = "original_post_url"
		case originalPostBody = "original_post_body"
		case reason
		case resolved
		case resolverId = "resolver_id"
		case published
		case updated
	}
}
