// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostFeatureType.swift

import Foundation

public enum PostFeatureType: String, Codable, CaseIterable, CustomStringConvertible {
	case local = "Local"
	case community = "Community"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract PostFeatureType from value \(value)"
			))
		}

		self = mode
	}
}
