// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostSavedForm.swift

import Foundation

public struct PostSavedForm: Codable {
	public var postId: Int
	public var personId: Int

	public init(postId: Int, personId: Int) {
		self.postId = postId
		self.personId = personId
	}

	public enum CodingKeys: String, CodingKey {
		case postId = "post_id"
		case personId = "person_id"
	}
}
