// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostAggregates.swift

import Foundation

public struct PostAggregates: Codable {
	public var id: Int32
	public var postId: Int
	public var comments: Int
	public var score: Int
	public var upvotes: Int
	public var downvotes: Int
	public var published: Date?
	public var newestCommentTimeNecro: Date?
	public var newestCommentTime: Date?
	public var featuredCommunity: Bool
	public var featuredLocal: Bool
	public var hotRank: Int32
	public var hotRankActive: Int32

	public init(
		id: Int32,
		postId: Int,
		comments: Int,
		score: Int,
		upvotes: Int,
		downvotes: Int,
		published: Date? = nil,
		newestCommentTimeNecro: Date? = nil,
		newestCommentTime: Date? = nil,
		featuredCommunity: Bool,
		featuredLocal: Bool,
		hotRank: Int32,
		hotRankActive: Int32
	) {
		self.id = id
		self.postId = postId
		self.comments = comments
		self.score = score
		self.upvotes = upvotes
		self.downvotes = downvotes
		self.published = published
		self.newestCommentTimeNecro = newestCommentTimeNecro
		self.newestCommentTime = newestCommentTime
		self.featuredCommunity = featuredCommunity
		self.featuredLocal = featuredLocal
		self.hotRank = hotRank
		self.hotRankActive = hotRankActive
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case postId = "post_id"
		case comments
		case score
		case upvotes
		case downvotes
		case published
		case newestCommentTimeNecro = "newest_comment_time_necro"
		case newestCommentTime = "newest_comment_time"
		case featuredCommunity = "featured_community"
		case featuredLocal = "featured_local"
		case hotRank = "hot_rank"
		case hotRankActive = "hot_rank_active"
	}
}
