// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostReportResponse.swift

import Foundation

public struct PostReportResponse: Codable {
	public var postReportView: PostReportView

	public init(postReportView: PostReportView) {
		self.postReportView = postReportView
	}

	public enum CodingKeys: String, CodingKey {
		case postReportView = "post_report_view"
	}
}
