// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Post.swift

import Foundation

public struct Post: Codable {
	public var id: Int
	public var name: String
	public var url: URL?
	public var body: String?
	public var creatorId: Int
	public var communityId: Int
	public var removed: Bool
	public var locked: Bool
	public var published: Date?
	public var updated: Date?
	public var deleted: Bool
	public var nsfw: Bool
	public var embedTitle: String?
	public var embedDescription: String?
	public var thumbnailURL: URL?
	public var apId: String
	public var local: Bool
	public var embedVideoURL: URL?
	public var languageId: Int
	public var featuredCommunity: Bool
	public var featuredLocal: Bool

	public init(
		id: Int,
		name: String,
		url: URL? = nil,
		body: String? = nil,
		creatorId: Int,
		communityId: Int,
		removed: Bool,
		locked: Bool,
		published: Date? = nil,
		updated: Date? = nil,
		deleted: Bool,
		nsfw: Bool,
		embedTitle: String? = nil,
		embedDescription: String? = nil,
		thumbnailURL: URL? = nil,
		apId: String,
		local: Bool,
		embedVideoURL: URL? = nil,
		languageId: Int,
		featuredCommunity: Bool,
		featuredLocal: Bool
	) {
		self.id = id
		self.name = name
		self.url = url
		self.body = body
		self.creatorId = creatorId
		self.communityId = communityId
		self.removed = removed
		self.locked = locked
		self.published = published
		self.updated = updated
		self.deleted = deleted
		self.nsfw = nsfw
		self.embedTitle = embedTitle
		self.embedDescription = embedDescription
		self.thumbnailURL = thumbnailURL
		self.apId = apId
		self.local = local
		self.embedVideoURL = embedVideoURL
		self.languageId = languageId
		self.featuredCommunity = featuredCommunity
		self.featuredLocal = featuredLocal
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case name
		case url
		case body
		case creatorId = "creator_id"
		case communityId = "community_id"
		case removed
		case locked
		case published
		case updated
		case deleted
		case nsfw
		case embedTitle = "embed_title"
		case embedDescription = "embed_description"
		case thumbnailURL = "thumbnail_url"
		case apId = "ap_id"
		case local
		case embedVideoURL = "embed_video_url"
		case languageId = "language_id"
		case featuredCommunity = "featured_community"
		case featuredLocal = "featured_local"
	}
}
