// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostResponse.swift

import Foundation

public struct PostResponse: Codable {
	public var postView: PostView

	public init(postView: PostView) {
		self.postView = postView
	}

	public enum CodingKeys: String, CodingKey {
		case postView = "post_view"
	}
}
