// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PostSaved.swift

import Foundation

public struct PostSaved: Codable {
	public var id: Int32
	public var postId: Int
	public var personId: Int
	public var published: Date?

	public init(id: Int32, postId: Int, personId: Int, published: Date? = nil) {
		self.id = id
		self.postId = postId
		self.personId = personId
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case postId = "post_id"
		case personId = "person_id"
		case published
	}
}
