// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessageReportResponse.swift

import Foundation

public struct PrivateMessageReportResponse: Codable {
	public var privateMessageReportView: PrivateMessageReportView

	public init(privateMessageReportView: PrivateMessageReportView) {
		self.privateMessageReportView = privateMessageReportView
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessageReportView = "private_message_report_view"
	}
}
