// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessageReport.swift

import Foundation

public struct PrivateMessageReport: Codable {
	public var id: Int
	public var creatorId: Int
	public var privateMessageId: Int
	public var originalPmText: String
	public var reason: String
	public var resolved: Bool
	public var resolverId: Int?
	public var published: Date?
	public var updated: Date?

	public init(
		id: Int,
		creatorId: Int,
		privateMessageId: Int,
		originalPmText: String,
		reason: String,
		resolved: Bool,
		resolverId: Int? = nil,
		published: Date? = nil,
		updated: Date? = nil
	) {
		self.id = id
		self.creatorId = creatorId
		self.privateMessageId = privateMessageId
		self.originalPmText = originalPmText
		self.reason = reason
		self.resolved = resolved
		self.resolverId = resolverId
		self.published = published
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case creatorId = "creator_id"
		case privateMessageId = "private_message_id"
		case originalPmText = "original_pm_text"
		case reason
		case resolved
		case resolverId = "resolver_id"
		case published
		case updated
	}
}
