// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessageReportForm.swift

import Foundation

public struct PrivateMessageReportForm: Codable {
	public var creatorId: Int
	public var privateMessageId: Int
	public var originalPmText: String
	public var reason: String

	public init(creatorId: Int, privateMessageId: Int, originalPmText: String, reason: String) {
		self.creatorId = creatorId
		self.privateMessageId = privateMessageId
		self.originalPmText = originalPmText
		self.reason = reason
	}

	public enum CodingKeys: String, CodingKey {
		case creatorId = "creator_id"
		case privateMessageId = "private_message_id"
		case originalPmText = "original_pm_text"
		case reason
	}
}
