// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessagesResponse.swift

import Foundation

public struct PrivateMessagesResponse: Codable {
	public var privateMessages: [PrivateMessageView]

	public init(privateMessages: [PrivateMessageView]) {
		self.privateMessages = privateMessages
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessages = "private_messages"
	}
}
