// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessageUpdateForm.swift

import Foundation

public struct PrivateMessageUpdateForm: Codable {
	public var content: String?
	public var deleted: Bool?
	public var read: Bool?
	public var published: Date?
	public var updated: Date?
	public var apId: String?
	public var local: Bool?

	public init(
		content: String? = nil,
		deleted: Bool? = nil,
		read: Bool? = nil,
		published: Date? = nil,
		updated: Date? = nil,
		apId: String? = nil,
		local: Bool? = nil
	) {
		self.content = content
		self.deleted = deleted
		self.read = read
		self.published = published
		self.updated = updated
		self.apId = apId
		self.local = local
	}

	public enum CodingKeys: String, CodingKey {
		case content
		case deleted
		case read
		case published
		case updated
		case apId = "ap_id"
		case local
	}
}
