// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PrivateMessageReportView.swift

import Foundation

public struct PrivateMessageReportView: Codable {
	public var privateMessageReport: PrivateMessageReport
	public var privateMessage: PrivateMessage
	public var privateMessageCreator: Person
	public var creator: Person
	public var resolver: Person?

	public init(
		privateMessageReport: PrivateMessageReport,
		privateMessage: PrivateMessage,
		privateMessageCreator: Person,
		creator: Person,
		resolver: Person? = nil
	) {
		self.privateMessageReport = privateMessageReport
		self.privateMessage = privateMessage
		self.privateMessageCreator = privateMessageCreator
		self.creator = creator
		self.resolver = resolver
	}

	public enum CodingKeys: String, CodingKey {
		case privateMessageReport = "private_message_report"
		case privateMessage = "private_message"
		case privateMessageCreator = "private_message_creator"
		case creator
		case resolver
	}
}
