// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: PurgeItemResponse.swift

import Foundation

public struct PurgeItemResponse: Codable {
	public var success: Bool

	public init(success: Bool) {
		self.success = success
	}

	public enum CodingKeys: String, CodingKey {
		case success
	}
}
