// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RegistrationApplication.swift

import Foundation

public struct RegistrationApplication: Codable {
	public var id: Int32
	public var localUserId: Int
	public var answer: String
	public var adminId: Int?
	public var denyReason: String?
	public var published: Date?

	public init(
		id: Int32,
		localUserId: Int,
		answer: String,
		adminId: Int? = nil,
		denyReason: String? = nil,
		published: Date? = nil
	) {
		self.id = id
		self.localUserId = localUserId
		self.answer = answer
		self.adminId = adminId
		self.denyReason = denyReason
		self.published = published
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case localUserId = "local_user_id"
		case answer
		case adminId = "admin_id"
		case denyReason = "deny_reason"
		case published
	}
}
