// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RegistrationMode.swift

import Foundation

public enum RegistrationMode: String, Codable, CaseIterable {
	case closed = "Closed"
	case requireapplication = "RequireApplication"
	case open = "Open"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract RegistrationMode from value \(value)"
			))
		}

		self = mode
	}
}
