// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RegistrationApplicationInsertForm.swift

import Foundation

public struct RegistrationApplicationInsertForm: Codable {
	public var localUserId: Int
	public var answer: String

	public init(localUserId: Int, answer: String) {
		self.localUserId = localUserId
		self.answer = answer
	}

	public enum CodingKeys: String, CodingKey {
		case localUserId = "local_user_id"
		case answer
	}
}
