// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RegistrationApplicationView.swift

import Foundation

public struct RegistrationApplicationView: Codable {
	public var registrationApplication: RegistrationApplication
	public var creatorLocalUser: LocalUser
	public var creator: Person
	public var admin: Person?

	public init(
		registrationApplication: RegistrationApplication,
		creatorLocalUser: LocalUser,
		creator: Person,
		admin: Person? = nil
	) {
		self.registrationApplication = registrationApplication
		self.creatorLocalUser = creatorLocalUser
		self.creator = creator
		self.admin = admin
	}

	public enum CodingKeys: String, CodingKey {
		case registrationApplication = "registration_application"
		case creatorLocalUser = "creator_local_user"
		case creator
		case admin
	}
}
