// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: RegistrationApplicationResponse.swift

import Foundation

public struct RegistrationApplicationResponse: Codable {
	public var registrationApplication: RegistrationApplicationView

	public init(registrationApplication: RegistrationApplicationView) {
		self.registrationApplication = registrationApplication
	}

	public enum CodingKeys: String, CodingKey {
		case registrationApplication = "registration_application"
	}
}
