// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: ResolveObjectResponse.swift

import Foundation

public struct ResolveObjectResponse: Codable {
	public var comment: CommentView?
	public var post: PostView?
	public var community: CommunityView?
	public var person: PersonView?

	public init(
		comment: CommentView? = nil,
		post: PostView? = nil,
		community: CommunityView? = nil,
		person: PersonView? = nil
	) {
		self.comment = comment
		self.post = post
		self.community = community
		self.person = person
	}

	public enum CodingKeys: String, CodingKey {
		case comment
		case post
		case community
		case person
	}
}
