// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SearchResponse.swift

import Foundation

public struct SearchResponse: Codable {
	public var type: SearchType
	public var comments: [CommentView]
	public var posts: [PostView]
	public var communities: [CommunityView]
	public var users: [PersonView]

	public init(
		type: SearchType,
		comments: [CommentView],
		posts: [PostView],
		communities: [CommunityView],
		users: [PersonView]
	) {
		self.type = type
		self.comments = comments
		self.posts = posts
		self.communities = communities
		self.users = users
	}

	public enum CodingKeys: String, CodingKey {
		case type = "type_"
		case comments
		case posts
		case communities
		case users
	}
}
