// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SearchType.swift

import Foundation

public enum SearchType: String, Codable, CaseIterable {
	case all = "All"
	case comments = "Comments"
	case posts = "Posts"
	case communities = "Communities"
	case users = "Users"
	case url = "Url"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract SearchType from value \(value)"
			))
		}

		self = mode
	}
}
