// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Secret.swift

import Foundation

public struct Secret: Codable {
	public var id: Int32
	public var jwtSecret: String

	public init(id: Int32, jwtSecret: String) {
		self.id = id
		self.jwtSecret = jwtSecret
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case jwtSecret = "jwt_secret"
	}
}
