// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteResponse.swift

import Foundation

public struct SiteResponse: Codable {
	public var siteView: SiteView
	public var taglines: [Tagline]

	public init(siteView: SiteView, taglines: [Tagline]) {
		self.siteView = siteView
		self.taglines = taglines
	}

	public enum CodingKeys: String, CodingKey {
		case siteView = "site_view"
		case taglines
	}
}
