// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteLanguageForm.swift

import Foundation

public struct SiteLanguageForm: Codable {
	public var siteId: Int
	public var languageId: Int

	public init(siteId: Int, languageId: Int) {
		self.siteId = siteId
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case siteId = "site_id"
		case languageId = "language_id"
	}
}
