// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteMetadata.swift

import Foundation

public struct SiteMetadata: Codable {
	public var title: String?
	public var description: String?
	public var embedVideoURL: URL?

	public init(title: String? = nil, description: String? = nil, embedVideoURL: URL? = nil) {
		self.title = title
		self.description = description
		self.embedVideoURL = embedVideoURL
	}

	public enum CodingKeys: String, CodingKey {
		case title
		case description
		case embedVideoURL = "embed_video_url"
	}
}
