// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteLanguage.swift

import Foundation

public struct SiteLanguage: Codable {
	public var id: Int
	public var siteId: Int
	public var languageId: Int

	public init(id: Int, siteId: Int, languageId: Int) {
		self.id = id
		self.siteId = siteId
		self.languageId = languageId
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case siteId = "site_id"
		case languageId = "language_id"
	}
}
