// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteAggregates.swift

import Foundation

public struct SiteAggregates: Codable {
	public var id: Int32
	public var siteId: Int
	public var users: Int
	public var posts: Int
	public var comments: Int
	public var communities: Int
	public var usersActiveDay: Int
	public var usersActiveWeek: Int
	public var usersActiveMonth: Int
	public var usersActiveHalfYear: Int

	public init(
		id: Int32,
		siteId: Int,
		users: Int,
		posts: Int,
		comments: Int,
		communities: Int,
		usersActiveDay: Int,
		usersActiveWeek: Int,
		usersActiveMonth: Int,
		usersActiveHalfYear: Int
	) {
		self.id = id
		self.siteId = siteId
		self.users = users
		self.posts = posts
		self.comments = comments
		self.communities = communities
		self.usersActiveDay = usersActiveDay
		self.usersActiveWeek = usersActiveWeek
		self.usersActiveMonth = usersActiveMonth
		self.usersActiveHalfYear = usersActiveHalfYear
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case siteId = "site_id"
		case users
		case posts
		case comments
		case communities
		case usersActiveDay = "users_active_day"
		case usersActiveWeek = "users_active_week"
		case usersActiveMonth = "users_active_month"
		case usersActiveHalfYear = "users_active_half_year"
	}
}
