// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SiteView.swift

import Foundation

public struct SiteView: Codable {
	public var site: Site
	public var localSite: LocalSite
	public var localSiteRateLimit: LocalSiteRateLimit
	public var counts: SiteAggregates

	public init(
		site: Site,
		localSite: LocalSite,
		localSiteRateLimit: LocalSiteRateLimit,
		counts: SiteAggregates
	) {
		self.site = site
		self.localSite = localSite
		self.localSiteRateLimit = localSiteRateLimit
		self.counts = counts
	}

	public enum CodingKeys: String, CodingKey {
		case site
		case localSite = "local_site"
		case localSiteRateLimit = "local_site_rate_limit"
		case counts
	}
}
