// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: SortType.swift

import Foundation

public enum SortType: String, Codable, CaseIterable, CustomStringConvertible {
	case active = "Active"
	case hot = "Hot"
	case new = "New"
	case old = "Old"
	case topday = "TopDay"
	case topweek = "TopWeek"
	case topmonth = "TopMonth"
	case topyear = "TopYear"
	case topall = "TopAll"
	case mostcomments = "MostComments"
	case newcomments = "NewComments"
	case tophour = "TopHour"
	case topsixhour = "TopSixHour"
	case toptwelvehour = "TopTwelveHour"
	case topthreemonths = "TopThreeMonths"
	case topsixmonths = "TopSixMonths"
	case topninemonths = "TopNineMonths"

	public var description: String {
		rawValue
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.singleValueContainer()
		let value = try container.decode(String.self)

		guard let mode = Self(caseInsensitiveRawValue: value) else {
			throw DecodingError.dataCorrupted(.init(
				codingPath: decoder.codingPath,
				debugDescription: "could not extract SortType from value \(value)"
			))
		}

		self = mode
	}
}
