// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: TaglineForm.swift

import Foundation

public struct TaglineForm: Codable {
	public var localSiteId: Int
	public var content: String
	public var updated: Date?

	public init(localSiteId: Int, content: String, updated: Date? = nil) {
		self.localSiteId = localSiteId
		self.content = content
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case localSiteId = "local_site_id"
		case content
		case updated
	}
}
