// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: Tagline.swift

import Foundation

public struct Tagline: Codable {
	public var id: Int32
	public var localSiteId: Int
	public var content: String
	public var published: Date?
	public var updated: Date?

	public init(
		id: Int32,
		localSiteId: Int,
		content: String,
		published: Date? = nil,
		updated: Date? = nil
	) {
		self.id = id
		self.localSiteId = localSiteId
		self.content = content
		self.published = published
		self.updated = updated
	}

	public enum CodingKeys: String, CodingKey {
		case id
		case localSiteId = "local_site_id"
		case content
		case published
		case updated
	}
}
