// This File was auto generated by LemmyKitCodeGen and should not be modified.
//
// File: VerifyEmailResponse.swift

import Foundation

public struct VerifyEmailResponse: Codable {
	public init() {}
}
